// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.implementation;

import com.azure.storage.blob.BlobServiceVersion;
import com.azure.storage.blob.models.EncryptionAlgorithmType;
import com.azure.storage.blob.models.FileShareTokenIntent;
import com.azure.storage.blob.models.ImmutabilityPolicyMode;
import com.azure.storage.blob.models.PageList;
import com.azure.storage.blob.models.PremiumPageBlobAccessTier;
import com.azure.storage.blob.models.SequenceNumberActionType;
import com.azure.storage.blob.models.StorageError;
import io.clientcore.core.annotations.ReturnType;
import io.clientcore.core.annotations.ServiceInterface;
import io.clientcore.core.annotations.ServiceMethod;
import io.clientcore.core.http.annotations.BodyParam;
import io.clientcore.core.http.annotations.HeaderParam;
import io.clientcore.core.http.annotations.HostParam;
import io.clientcore.core.http.annotations.HttpRequestInformation;
import io.clientcore.core.http.annotations.PathParam;
import io.clientcore.core.http.annotations.QueryParam;
import io.clientcore.core.http.annotations.UnexpectedResponseExceptionDetail;
import io.clientcore.core.http.models.HttpMethod;
import io.clientcore.core.http.models.HttpRequestConditions;
import io.clientcore.core.http.models.HttpResponseException;
import io.clientcore.core.http.models.RequestContext;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.http.pipeline.HttpPipeline;
import io.clientcore.core.instrumentation.Instrumentation;
import io.clientcore.core.models.binarydata.BinaryData;
import io.clientcore.core.utils.DateTimeRfc1123;
import java.lang.reflect.InvocationTargetException;
import java.time.OffsetDateTime;
import java.util.Base64;

/**
 * An instance of this class provides access to all the operations defined in ContainerBlobPageBlobs.
 */
public final class ContainerBlobPageBlobsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final ContainerBlobPageBlobsService service;

    /**
     * The service client containing this operation class.
     */
    private final BlobClientImpl client;

    /**
     * The instance of instrumentation to report telemetry.
     */
    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of ContainerBlobPageBlobsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    ContainerBlobPageBlobsImpl(BlobClientImpl client) {
        this.service = ContainerBlobPageBlobsService.getNewInstance(client.getHttpPipeline());
        this.client = client;
        this.instrumentation = client.getInstrumentation();
    }

    /**
     * Gets Service version.
     * 
     * @return the serviceVersion value.
     */
    public BlobServiceVersion getServiceVersion() {
        return client.getServiceVersion();
    }

    /**
     * The interface defining all the services for BlobClientContainerBlobPageBlobs to be used by the proxy service to
     * perform REST calls.
     */
    @ServiceInterface(name = "BlobClientContainerBlobPageBlobs", host = "{url}")
    public interface ContainerBlobPageBlobsService {
        static ContainerBlobPageBlobsService getNewInstance(HttpPipeline pipeline) {
            try {
                Class<?> clazz
                    = Class.forName("com.azure.storage.blob.implementation.ContainerBlobPageBlobsServiceImpl");
                return (ContainerBlobPageBlobsService) clazz.getMethod("getNewInstance", HttpPipeline.class)
                    .invoke(null, pipeline);
            } catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException
                | InvocationTargetException e) {
                throw new RuntimeException(e);
            }

        }

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}",
            expectedStatusCodes = { 201 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> create(@HostParam("url") String url, @HeaderParam("x-ms-version") String xMsVersion,
            @HeaderParam("x-ms-meta") String metadata, @PathParam("containerName") String containerName,
            @PathParam("blobName") String blobName, @QueryParam("timeout") Integer timeout,
            @HeaderParam("x-ms-access-tier") PremiumPageBlobAccessTier tier,
            @HeaderParam("x-ms-blob-content-type") String blobContentType,
            @HeaderParam("x-ms-blob-content-encoding") String blobContentEncoding,
            @HeaderParam("x-ms-blob-content-language") String blobContentLanguage,
            @HeaderParam("x-ms-blob-content-md5") String blobContentMd5,
            @HeaderParam("x-ms-blob-cache-control") String blobCacheControl,
            @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("x-ms-blob-content-disposition") String blobContentDisposition,
            @HeaderParam("x-ms-encryption-key") String encryptionKey,
            @HeaderParam("x-ms-encryption-key-sha256") String encryptionKeySha256,
            @HeaderParam("x-ms-encryption-algorithm") EncryptionAlgorithmType encryptionAlgorithm,
            @HeaderParam("x-ms-encryption-scope") String encryptionScope,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @HeaderParam("x-ms-blob-content-length") long blobContentLength,
            @HeaderParam("x-ms-blob-sequence-number") Long blobSequenceNumber,
            @HeaderParam("x-ms-tags") String blobTagsString,
            @HeaderParam("x-ms-immutability-policy-until-date") DateTimeRfc1123 immutabilityPolicyExpiry,
            @HeaderParam("x-ms-immutability-policy-mode") ImmutabilityPolicyMode immutabilityPolicyMode,
            @HeaderParam("x-ms-legal-hold") Boolean legalHold, @HeaderParam("Content-Length") int contentLength,
            @HeaderParam("x-ms-blob-type") String blobType, @HeaderParam("Accept") String accept,
            RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}?comp=page&update",
            expectedStatusCodes = { 201 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> uploadPages(@HostParam("url") String url, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("x-ms-version") String xMsVersion, @PathParam("containerName") String containerName,
            @PathParam("blobName") String blobName, @HeaderParam("Content-Length") long contentLength,
            @HeaderParam("Content-MD5") String transactionalContentMD5,
            @HeaderParam("x-ms-content-crc64") String transactionalContentCrc64, @QueryParam("timeout") Integer timeout,
            @HeaderParam("Range") String range, @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("x-ms-encryption-key") String encryptionKey,
            @HeaderParam("x-ms-encryption-key-sha256") String encryptionKeySha256,
            @HeaderParam("x-ms-encryption-algorithm") EncryptionAlgorithmType encryptionAlgorithm,
            @HeaderParam("x-ms-encryption-scope") String encryptionScope,
            @HeaderParam("x-ms-if-sequence-number-le") Long ifSequenceNumberLessThanOrEqualTo,
            @HeaderParam("x-ms-if-sequence-number-lt") Long ifSequenceNumberLessThan,
            @HeaderParam("x-ms-if-sequence-number-eq") Long ifSequenceNumberEqualTo,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @HeaderParam("x-ms-structured-body") String structuredBodyType,
            @HeaderParam("x-ms-structured-content-length") Long structuredContentLength,
            @HeaderParam("x-ms-page-write") String pageWrite, @HeaderParam("Accept") String accept,
            @BodyParam("application/octet-stream") BinaryData body, RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}?comp=page&clear",
            expectedStatusCodes = { 201 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> clearPages(@HostParam("url") String url, @HeaderParam("x-ms-version") String xMsVersion,
            @PathParam("containerName") String containerName, @PathParam("blobName") String blobName,
            @HeaderParam("Content-Length") int contentLength, @QueryParam("timeout") Integer timeout,
            @HeaderParam("Range") String range, @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("x-ms-encryption-key") String encryptionKey,
            @HeaderParam("x-ms-encryption-key-sha256") String encryptionKeySha256,
            @HeaderParam("x-ms-encryption-algorithm") EncryptionAlgorithmType encryptionAlgorithm,
            @HeaderParam("x-ms-encryption-scope") String encryptionScope,
            @HeaderParam("x-ms-if-sequence-number-le") Long ifSequenceNumberLessThanOrEqualTo,
            @HeaderParam("x-ms-if-sequence-number-lt") Long ifSequenceNumberLessThan,
            @HeaderParam("x-ms-if-sequence-number-eq") Long ifSequenceNumberEqualTo,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @HeaderParam("x-ms-page-write") String pageWrite,
            @HeaderParam("Accept") String accept, RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}?comp=page&update&fromUrl",
            expectedStatusCodes = { 201 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> uploadPagesFromUrl(@HostParam("url") String url, @HeaderParam("x-ms-version") String xMsVersion,
            @PathParam("containerName") String containerName, @PathParam("blobName") String blobName,
            @HeaderParam("x-ms-copy-source") String sourceUrl, @HeaderParam("x-ms-source-range") String sourceRange,
            @HeaderParam("x-ms-source-content-md5") String sourceContentMd5,
            @HeaderParam("x-ms-source-content-crc64") String sourceContentCrc64,
            @HeaderParam("Content-Length") long contentLength, @QueryParam("timeout") Integer timeout,
            @HeaderParam("x-ms-range") String range, @HeaderParam("x-ms-encryption-key") String encryptionKey,
            @HeaderParam("x-ms-encryption-key-sha256") String encryptionKeySha256,
            @HeaderParam("x-ms-encryption-algorithm") EncryptionAlgorithmType encryptionAlgorithm,
            @HeaderParam("x-ms-encryption-scope") String encryptionScope, @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("x-ms-if-sequence-number-le") Long ifSequenceNumberLessThanOrEqualTo,
            @HeaderParam("x-ms-if-sequence-number-lt") Long ifSequenceNumberLessThan,
            @HeaderParam("x-ms-if-sequence-number-eq") Long ifSequenceNumberEqualTo,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags,
            @HeaderParam("x-ms-source-if-modified-since") DateTimeRfc1123 sourceIfModifiedSince,
            @HeaderParam("x-ms-source-if-unmodified-since") DateTimeRfc1123 sourceIfUnmodifiedSince,
            @HeaderParam("x-ms-source-if-match") String sourceIfMatch,
            @HeaderParam("x-ms-source-if-none-match") String sourceIfNoneMatch,
            @HeaderParam("x-ms-copy-source-authorization") String copySourceAuthorization,
            @HeaderParam("x-ms-file-request-intent") FileShareTokenIntent fileRequestIntent,
            @HeaderParam("x-ms-page-write") String pageWrite, @HeaderParam("Accept") String accept,
            RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/{containerName}/{blobName}?comp=pagelist",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<PageList> getPageRanges(@HostParam("url") String url, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("x-ms-version") String xMsVersion, @PathParam("containerName") String containerName,
            @PathParam("blobName") String blobName, @QueryParam("snapshot") String snapshot,
            @QueryParam("timeout") Integer timeout, @HeaderParam("Range") String range,
            @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @QueryParam("marker") String marker,
            @QueryParam("maxresults") Integer maxresults, @HeaderParam("Accept") String accept,
            RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/{containerName}/{blobName}?comp=pagelist&diff",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<PageList> getPageRangesDiff(@HostParam("url") String url,
            @HeaderParam("Content-Type") String contentType, @HeaderParam("x-ms-version") String xMsVersion,
            @PathParam("containerName") String containerName, @PathParam("blobName") String blobName,
            @QueryParam("snapshot") String snapshot, @QueryParam("timeout") Integer timeout,
            @QueryParam("prevsnapshot") String prevsnapshot,
            @HeaderParam("x-ms-previous-snapshot-url") String prevSnapshotUrl, @HeaderParam("Range") String range,
            @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @QueryParam("marker") String marker,
            @QueryParam("maxresults") Integer maxresults, @HeaderParam("Accept") String accept,
            RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}?comp=properties&Resize",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> resize(@HostParam("url") String url, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("x-ms-version") String xMsVersion, @PathParam("containerName") String containerName,
            @PathParam("blobName") String blobName, @QueryParam("timeout") Integer timeout,
            @HeaderParam("x-ms-lease-id") String leaseId, @HeaderParam("x-ms-encryption-key") String encryptionKey,
            @HeaderParam("x-ms-encryption-key-sha256") String encryptionKeySha256,
            @HeaderParam("x-ms-encryption-algorithm") EncryptionAlgorithmType encryptionAlgorithm,
            @HeaderParam("x-ms-encryption-scope") String encryptionScope,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @HeaderParam("x-ms-blob-content-length") long blobContentLength,
            @HeaderParam("Accept") String accept, RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}?comp=properties&UpdateSequenceNumber",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> updateSequenceNumber(@HostParam("url") String url,
            @HeaderParam("Content-Type") String contentType, @HeaderParam("x-ms-version") String xMsVersion,
            @PathParam("containerName") String containerName, @PathParam("blobName") String blobName,
            @QueryParam("timeout") Integer timeout, @HeaderParam("x-ms-lease-id") String leaseId,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags,
            @HeaderParam("x-ms-sequence-number-action") SequenceNumberActionType sequenceNumberAction,
            @HeaderParam("x-ms-blob-sequence-number") Long blobSequenceNumber, @HeaderParam("Accept") String accept,
            RequestContext requestContext);

        @HttpRequestInformation(
            method = HttpMethod.PUT,
            path = "/{containerName}/{blobName}?comp=incrementalcopy",
            expectedStatusCodes = { 202 })
        @UnexpectedResponseExceptionDetail(exceptionBodyClass = StorageError.class)
        Response<Void> copyIncremental(@HostParam("url") String url, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("x-ms-version") String xMsVersion, @PathParam("containerName") String containerName,
            @PathParam("blobName") String blobName, @QueryParam("timeout") Integer timeout,
            @HeaderParam("If-Modified-Since") DateTimeRfc1123 ifModifiedSince,
            @HeaderParam("If-Unmodified-Since") DateTimeRfc1123 ifUnmodifiedSince,
            @HeaderParam("If-None-Match") String ifNoneMatch, @HeaderParam("If-Match") String ifMatch,
            @HeaderParam("x-ms-if-tags") String ifTags, @HeaderParam("x-ms-copy-source") String copySource,
            @HeaderParam("Accept") String accept, RequestContext requestContext);
    }

    /**
     * The Create operation creates a new page blob.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @param metadata The metadata headers.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param tier Optional. Indicates the tier to be set on the page blob.
     * @param blobContentType Optional. Sets the blob's content type. If specified, this property is stored with the
     * blob and returned with a read request.
     * @param blobContentEncoding Optional. Sets the blob's content encoding. If specified, this property is stored with
     * the blob and returned with a read request.
     * @param blobContentLanguage Optional. Set the blob's content language. If specified, this property is stored with
     * the blob and returned with a read request.
     * @param blobContentMd5 Optional. An MD5 hash of the blob content. Note that this hash is not validated, as the
     * hashes for the individual blocks were validated when each was uploaded.
     * @param blobCacheControl Optional. Sets the blob's cache control. If specified, this property is stored with the
     * blob and returned with a read request.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param blobContentDisposition Optional. Sets the blob's content disposition. If specified, this property is
     * stored with the blob and returned with a read request.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param blobSequenceNumber Set for page blobs only. The sequence number is a user-controlled value that you can
     * use to track requests. The value of the sequence number must be between 0 and 2^63 - 1.
     * @param blobTagsString Optional. Used to set blob tags in various blob operations.
     * @param immutabilityPolicyExpiry Specifies the date time when the blobs immutability policy is set to expire.
     * @param immutabilityPolicyMode Specifies the immutability policy mode to set on the blob.
     * @param legalHold Specified if a legal hold should be set on the blob.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> createWithResponse(long blobContentLength, String metadata, Integer timeout,
        PremiumPageBlobAccessTier tier, String blobContentType, String blobContentEncoding, String blobContentLanguage,
        byte[] blobContentMd5, String blobCacheControl, String leaseId, String blobContentDisposition,
        String encryptionKey, String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm,
        String encryptionScope, String ifTags, Long blobSequenceNumber, String blobTagsString,
        OffsetDateTime immutabilityPolicyExpiry, ImmutabilityPolicyMode immutabilityPolicyMode, Boolean legalHold,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.create",
            requestContext, updatedContext -> {
                final int contentLength = 0;
                final String blobType = "PageBlob";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                String blobContentMd5Converted = new String(Base64.getEncoder().encode(blobContentMd5));
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                DateTimeRfc1123 immutabilityPolicyExpiryConverted
                    = immutabilityPolicyExpiry == null ? null : new DateTimeRfc1123(immutabilityPolicyExpiry);
                return service.create(this.client.getUrl(), this.client.getServiceVersion().getVersion(), metadata,
                    this.client.getContainerName(), this.client.getBlobName(), timeout, tier, blobContentType,
                    blobContentEncoding, blobContentLanguage, blobContentMd5Converted, blobCacheControl, leaseId,
                    blobContentDisposition, encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
                    ifModifiedSinceConverted, ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch, ifTags,
                    blobContentLength, blobSequenceNumber, blobTagsString, immutabilityPolicyExpiryConverted,
                    immutabilityPolicyMode, legalHold, contentLength, blobType, accept, updatedContext);
            });
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob.
     * 
     * @param contentLength The length of the request.
     * @param range Bytes of data in the specified range.
     * @param body The body of the request.
     * @param transactionalContentMD5 Optional. An MD5 hash of the blob content. Note that this hash is not validated,
     * as the hashes for the individual blocks were validated when each was uploaded.
     * @param transactionalContentCrc64 Specify the transactional crc64 for the body, to be validated by the service.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param structuredBodyType Required if the request body is a structured message. Specifies the message schema
     * version and properties.
     * @param structuredContentLength Required if the request body is a structured message. Specifies the length of the
     * blob/file content inside the message body. Will always be smaller than Content-Length.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> uploadPagesWithResponse(long contentLength, String range, BinaryData body,
        byte[] transactionalContentMD5, byte[] transactionalContentCrc64, Integer timeout, String leaseId,
        String encryptionKey, String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm,
        String encryptionScope, Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan,
        Long ifSequenceNumberEqualTo, String ifTags, String structuredBodyType, Long structuredContentLength,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.uploadPages",
            requestContext, updatedContext -> {
                final String contentType = "application/octet-stream";
                final String pageWrite = "update";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                String transactionalContentMD5Converted
                    = new String(Base64.getEncoder().encode(transactionalContentMD5));
                String transactionalContentCrc64Converted
                    = new String(Base64.getEncoder().encode(transactionalContentCrc64));
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.uploadPages(this.client.getUrl(), contentType,
                    this.client.getServiceVersion().getVersion(), this.client.getContainerName(),
                    this.client.getBlobName(), contentLength, transactionalContentMD5Converted,
                    transactionalContentCrc64Converted, timeout, range, leaseId, encryptionKey, encryptionKeySha256,
                    encryptionAlgorithm, encryptionScope, ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan,
                    ifSequenceNumberEqualTo, ifModifiedSinceConverted, ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch,
                    ifTags, structuredBodyType, structuredContentLength, pageWrite, accept, body, updatedContext);
            });
    }

    /**
     * The Clear Pages operation clears a range of pages from a page blob.
     * 
     * @param range Bytes of data in the specified range.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> clearPagesWithResponse(String range, Integer timeout, String leaseId, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.clearPages",
            requestContext, updatedContext -> {
                final int contentLength = 0;
                final String pageWrite = "clear";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.clearPages(this.client.getUrl(), this.client.getServiceVersion().getVersion(),
                    this.client.getContainerName(), this.client.getBlobName(), contentLength, timeout, range, leaseId,
                    encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
                    ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo,
                    ifModifiedSinceConverted, ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch, ifTags, pageWrite,
                    accept, updatedContext);
            });
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob where the contents are read from a URL.
     * 
     * @param sourceUrl Specify a URL to the copy source.
     * @param sourceRange Bytes of source data in the specified range. The length of this range should match the
     * ContentLength header and x-ms-range/Range destination range header.
     * @param contentLength The length of the request.
     * @param range Bytes of source data in the specified range. The length of this range should match the ContentLength
     * header and x-ms-range/Range destination range header.
     * @param sourceContentMd5 Specify the md5 calculated for the range of bytes that must be read from the copy source.
     * @param sourceContentCrc64 Specify the crc64 calculated for the range of bytes that must be read from the copy
     * source.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param sourceIfModifiedSince Specify this header value to operate only on a blob if it has been modified since
     * the specified date/time.
     * @param sourceIfUnmodifiedSince Specify this header value to operate only on a blob if it has not been modified
     * since the specified date/time.
     * @param sourceIfMatch Specify an ETag value to operate only on blobs with a matching value.
     * @param sourceIfNoneMatch Specify this header value to operate only on a blob if it has been modified since the
     * specified date/time.
     * @param copySourceAuthorization Only Bearer type is supported. Credentials should be a valid OAuth access token to
     * copy source.
     * @param fileRequestIntent Valid value is backup.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> uploadPagesFromUrlWithResponse(String sourceUrl, String sourceRange, long contentLength,
        String range, byte[] sourceContentMd5, byte[] sourceContentCrc64, Integer timeout, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope, String leaseId,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, OffsetDateTime sourceIfModifiedSince, OffsetDateTime sourceIfUnmodifiedSince,
        String sourceIfMatch, String sourceIfNoneMatch, String copySourceAuthorization,
        FileShareTokenIntent fileRequestIntent, HttpRequestConditions requestConditions,
        RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.uploadPagesFromUrl",
            requestContext, updatedContext -> {
                final String pageWrite = "update";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                String sourceContentMd5Converted = new String(Base64.getEncoder().encode(sourceContentMd5));
                String sourceContentCrc64Converted = new String(Base64.getEncoder().encode(sourceContentCrc64));
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                DateTimeRfc1123 sourceIfModifiedSinceConverted
                    = sourceIfModifiedSince == null ? null : new DateTimeRfc1123(sourceIfModifiedSince);
                DateTimeRfc1123 sourceIfUnmodifiedSinceConverted
                    = sourceIfUnmodifiedSince == null ? null : new DateTimeRfc1123(sourceIfUnmodifiedSince);
                return service.uploadPagesFromUrl(this.client.getUrl(), this.client.getServiceVersion().getVersion(),
                    this.client.getContainerName(), this.client.getBlobName(), sourceUrl, sourceRange,
                    sourceContentMd5Converted, sourceContentCrc64Converted, contentLength, timeout, range,
                    encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope, leaseId,
                    ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo,
                    ifModifiedSinceConverted, ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch, ifTags,
                    sourceIfModifiedSinceConverted, sourceIfUnmodifiedSinceConverted, sourceIfMatch, sourceIfNoneMatch,
                    copySourceAuthorization, fileRequestIntent, pageWrite, accept, updatedContext);
            });
    }

    /**
     * The Get Page Ranges operation returns the list of valid page ranges for a page blob or snapshot of a page blob.
     * 
     * @param snapshot The snapshot parameter is an opaque DateTime value that, when present, specifies the blob
     * snapshot to retrieve. For more information on working with blob snapshots, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating
     * a Snapshot of a Blob.&lt;/a&gt;.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param range Return only the bytes of the blob in the specified range.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param marker A string value that identifies the portion of the list of containers to be returned with the next
     * listing operation. The operation returns the NextMarker value within the response body if the listing operation
     * did not return all containers remaining to be listed with the current page. The NextMarker value can be used as
     * the value for the marker parameter in a subsequent call to request the next page of list items. The marker value
     * is opaque to the client.
     * @param maxresults Specifies the maximum number of containers to return. If the request does not specify
     * maxresults, or specifies a value greater than 5000, the server will return up to 5000 items.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<PageList> getPageRangesWithResponse(String snapshot, Integer timeout, String range, String leaseId,
        String ifTags, String marker, Integer maxresults, HttpRequestConditions requestConditions,
        RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.getPageRanges",
            requestContext, updatedContext -> {
                final String contentType = "application/xml";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.getPageRanges(this.client.getUrl(), contentType,
                    this.client.getServiceVersion().getVersion(), this.client.getContainerName(),
                    this.client.getBlobName(), snapshot, timeout, range, leaseId, ifModifiedSinceConverted,
                    ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch, ifTags, marker, maxresults, accept,
                    updatedContext);
            });
    }

    /**
     * The Get Page Ranges Diff operation returns the list of valid page ranges for a page blob or snapshot of a page
     * blob.
     * 
     * @param snapshot The snapshot parameter is an opaque DateTime value that, when present, specifies the blob
     * snapshot to retrieve. For more information on working with blob snapshots, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating
     * a Snapshot of a Blob.&lt;/a&gt;.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param prevsnapshot Optional in version 2015-07-08 and newer. The prevsnapshot parameter is a DateTime value that
     * specifies that the response will contain only pages that were changed between target blob and previous snapshot.
     * Changed pages include both updated and cleared pages. The target blob may be a snapshot, as long as the snapshot
     * specified by prevsnapshot is the older of the two. Note that incremental snapshots are currently supported only
     * for blobs created on or after January 1, 2016.
     * @param prevSnapshotUrl Optional. This header is only supported in service versions 2019-04-19 and after and
     * specifies the URL of a previous snapshot of the target blob. The response will only contain pages that were
     * changed between the target blob and its previous snapshot.
     * @param range Return only the bytes of the blob in the specified range.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param marker A string value that identifies the portion of the list of containers to be returned with the next
     * listing operation. The operation returns the NextMarker value within the response body if the listing operation
     * did not return all containers remaining to be listed with the current page. The NextMarker value can be used as
     * the value for the marker parameter in a subsequent call to request the next page of list items. The marker value
     * is opaque to the client.
     * @param maxresults Specifies the maximum number of containers to return. If the request does not specify
     * maxresults, or specifies a value greater than 5000, the server will return up to 5000 items.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<PageList> getPageRangesDiffWithResponse(String snapshot, Integer timeout, String prevsnapshot,
        String prevSnapshotUrl, String range, String leaseId, String ifTags, String marker, Integer maxresults,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.getPageRangesDiff",
            requestContext, updatedContext -> {
                final String contentType = "application/xml";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.getPageRangesDiff(this.client.getUrl(), contentType,
                    this.client.getServiceVersion().getVersion(), this.client.getContainerName(),
                    this.client.getBlobName(), snapshot, timeout, prevsnapshot, prevSnapshotUrl, range, leaseId,
                    ifModifiedSinceConverted, ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch, ifTags, marker,
                    maxresults, accept, updatedContext);
            });
    }

    /**
     * The Resize operation increases the size of the page blob to the specified size.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> resizeWithResponse(long blobContentLength, Integer timeout, String leaseId,
        String encryptionKey, String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm,
        String encryptionScope, String ifTags, HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.resize",
            requestContext, updatedContext -> {
                final String contentType = "application/xml";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.resize(this.client.getUrl(), contentType, this.client.getServiceVersion().getVersion(),
                    this.client.getContainerName(), this.client.getBlobName(), timeout, leaseId, encryptionKey,
                    encryptionKeySha256, encryptionAlgorithm, encryptionScope, ifModifiedSinceConverted,
                    ifUnmodifiedSinceConverted, ifNoneMatch, ifMatch, ifTags, blobContentLength, accept,
                    updatedContext);
            });
    }

    /**
     * The Update Sequence Number operation sets the blob's sequence number. The operation will fail if the specified
     * sequence number is less than the current sequence number of the blob.
     * 
     * @param sequenceNumberAction Required if the x-ms-blob-sequence-number header is set for the request. This
     * property applies to page blobs only. This property indicates how the service should modify the blob's sequence
     * number.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param blobSequenceNumber Set for page blobs only. The sequence number is a user-controlled value that you can
     * use to track requests. The value of the sequence number must be between 0 and 2^63 - 1.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> updateSequenceNumberWithResponse(SequenceNumberActionType sequenceNumberAction,
        Integer timeout, String leaseId, String ifTags, Long blobSequenceNumber,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.updateSequenceNumber",
            requestContext, updatedContext -> {
                final String contentType = "application/xml";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.updateSequenceNumber(this.client.getUrl(), contentType,
                    this.client.getServiceVersion().getVersion(), this.client.getContainerName(),
                    this.client.getBlobName(), timeout, leaseId, ifModifiedSinceConverted, ifUnmodifiedSinceConverted,
                    ifNoneMatch, ifMatch, ifTags, sequenceNumberAction, blobSequenceNumber, accept, updatedContext);
            });
    }

    /**
     * The Copy Incremental operation copies a snapshot of the source page blob to a destination page blob. The snapshot
     * is copied such that only the differential changes between the previously copied snapshot are transferred to the
     * destination. The copied snapshots are complete copies of the original snapshot and can be read or copied from as
     * usual. This API is supported since REST version 2016-05-31.
     * 
     * @param copySource Specifies the name of the source page blob snapshot. This value is a URL of up to 2 KB in
     * length that specifies a page blob snapshot. The value should be URL-encoded as it would appear in a request URI.
     * The source blob must either be public or must be authenticated via a shared access signature.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> copyIncrementalWithResponse(String copySource, Integer timeout, String ifTags,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.copyIncremental",
            requestContext, updatedContext -> {
                final String contentType = "application/xml";
                final String accept = "application/xml";
                OffsetDateTime ifModifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifModifiedSinceInternal = requestConditions.getIfModifiedSince();
                }
                OffsetDateTime ifModifiedSince = ifModifiedSinceInternal;
                OffsetDateTime ifUnmodifiedSinceInternal = null;
                if (requestConditions != null) {
                    ifUnmodifiedSinceInternal = requestConditions.getIfUnmodifiedSince();
                }
                OffsetDateTime ifUnmodifiedSince = ifUnmodifiedSinceInternal;
                String ifNoneMatchInternal = null;
                if (requestConditions != null) {
                    ifNoneMatchInternal = requestConditions.getIfNoneMatch();
                }
                String ifNoneMatch = ifNoneMatchInternal;
                String ifMatchInternal = null;
                if (requestConditions != null) {
                    ifMatchInternal = requestConditions.getIfMatch();
                }
                String ifMatch = ifMatchInternal;
                DateTimeRfc1123 ifModifiedSinceConverted
                    = ifModifiedSince == null ? null : new DateTimeRfc1123(ifModifiedSince);
                DateTimeRfc1123 ifUnmodifiedSinceConverted
                    = ifUnmodifiedSince == null ? null : new DateTimeRfc1123(ifUnmodifiedSince);
                return service.copyIncremental(this.client.getUrl(), contentType,
                    this.client.getServiceVersion().getVersion(), this.client.getContainerName(),
                    this.client.getBlobName(), timeout, ifModifiedSinceConverted, ifUnmodifiedSinceConverted,
                    ifNoneMatch, ifMatch, ifTags, copySource, accept, updatedContext);
            });
    }
}
