// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.implementation;

import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceInterface;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.annotation.BodyParam;
import com.generic.core.http.annotation.HeaderParam;
import com.generic.core.http.annotation.HttpRequestInformation;
import com.generic.core.http.annotation.UnexpectedResponseExceptionInformation;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.HttpMethod;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.implementation.http.RestProxy;
import com.generic.core.implementation.http.rest.RestProxyUtils;
import com.generic.core.models.BinaryData;
import com.generic.core.models.Context;

/**
 * An instance of this class provides access to all the operations defined in Completions.
 */
public final class CompletionsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final CompletionsService service;

    /**
     * The service client containing this operation class.
     */
    private final OpenAiClientImpl client;

    /**
     * Initializes an instance of CompletionsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    CompletionsImpl(OpenAiClientImpl client) {
        this.service = RestProxy.create(CompletionsService.class, client.getHttpPipeline(),
            RestProxyUtils.createDefaultSerializer());
        this.client = client;
    }

    /**
     * The interface defining all the services for OpenAiClientCompletions to be used by the proxy service to perform
     * REST calls.
     */
    @ServiceInterface(name = "OpenAiClientCompleti", host = "https://api.openai.com/v1")
    public interface CompletionsService {
        @HttpRequestInformation(method = HttpMethod.POST, path = "/completions", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> createCompletionSync(@HeaderParam("accept") String accept,
            @BodyParam("application/json") BinaryData createCompletionRequest, RequestOptions requestOptions,
            Context context);
    }

    /**
     * The createCompletion operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     model: String(babbage-002/davinci-002/text-davinci-003/text-davinci-002/text-davinci-001/code-davinci-002/text-curie-001/text-babbage-001/text-ada-001) (Required)
     *     prompt: BinaryData (Required)
     *     suffix: String (Optional)
     *     temperature: Double (Optional)
     *     top_p: Double (Optional)
     *     n: Long (Optional)
     *     max_tokens: Long (Optional)
     *     stop: BinaryData (Optional)
     *     presence_penalty: Double (Optional)
     *     frequency_penalty: Double (Optional)
     *     logit_bias (Optional): {
     *         String: long (Required)
     *     }
     *     user: String (Optional)
     *     stream: Boolean (Optional)
     *     logprobs: Long (Optional)
     *     echo: Boolean (Optional)
     *     best_of: Long (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created: long (Required)
     *     model: String (Required)
     *     choices (Required): [
     *          (Required){
     *             index: long (Required)
     *             text: String (Required)
     *             logprobs (Required): {
     *                 tokens (Required): [
     *                     String (Required)
     *                 ]
     *                 token_logprobs (Required): [
     *                     double (Required)
     *                 ]
     *                 top_logprobs (Required): [
     *                      (Required){
     *                         String: long (Required)
     *                     }
     *                 ]
     *                 text_offset (Required): [
     *                     long (Required)
     *                 ]
     *             }
     *             finish_reason: String(stop/length/content_filter) (Required)
     *         }
     *     ]
     *     usage (Optional): {
     *         prompt_tokens: long (Required)
     *         completion_tokens: long (Required)
     *         total_tokens: long (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param createCompletionRequest The createCompletionRequest parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return represents a completion response from the API.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createCompletionWithResponse(BinaryData createCompletionRequest,
        RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.createCompletionSync(accept, createCompletionRequest, requestOptions, Context.NONE);
    }
}
