// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.implementation;

import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceInterface;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.annotation.BodyParam;
import com.generic.core.http.annotation.HeaderParam;
import com.generic.core.http.annotation.HttpRequestInformation;
import com.generic.core.http.annotation.UnexpectedResponseExceptionInformation;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.HttpMethod;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.implementation.http.RestProxy;
import com.generic.core.implementation.http.rest.RestProxyUtils;
import com.generic.core.models.BinaryData;
import com.generic.core.models.Context;

/**
 * An instance of this class provides access to all the operations defined in Edits.
 */
public final class EditsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final EditsService service;

    /**
     * The service client containing this operation class.
     */
    private final OpenAiClientImpl client;

    /**
     * Initializes an instance of EditsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    EditsImpl(OpenAiClientImpl client) {
        this.service
            = RestProxy.create(EditsService.class, client.getHttpPipeline(), RestProxyUtils.createDefaultSerializer());
        this.client = client;
    }

    /**
     * The interface defining all the services for OpenAiClientEdits to be used by the proxy service to perform REST
     * calls.
     */
    @ServiceInterface(name = "OpenAiClientEdits", host = "https://api.openai.com/v1")
    public interface EditsService {
        @HttpRequestInformation(method = HttpMethod.POST, path = "/edits", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> createEditSync(@HeaderParam("accept") String accept,
            @BodyParam("application/json") BinaryData edit, RequestOptions requestOptions, Context context);
    }

    /**
     * The createEdit operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     model: String(text-davinci-edit-001/code-davinci-edit-001) (Required)
     *     input: String (Optional)
     *     instruction: String (Required)
     *     n: Long (Optional)
     *     temperature: Double (Optional)
     *     top_p: Double (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     object: String (Required)
     *     created: long (Required)
     *     choices (Required): [
     *          (Required){
     *             text: String (Required)
     *             index: long (Required)
     *             finish_reason: String(stop/length) (Required)
     *         }
     *     ]
     *     usage (Required): {
     *         prompt_tokens: long (Required)
     *         completion_tokens: long (Required)
     *         total_tokens: long (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param edit The edit parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createEditWithResponse(BinaryData edit, RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.createEditSync(accept, edit, requestOptions, Context.NONE);
    }
}
