// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.implementation;

import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceInterface;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.annotation.BodyParam;
import com.generic.core.http.annotation.HeaderParam;
import com.generic.core.http.annotation.HttpRequestInformation;
import com.generic.core.http.annotation.UnexpectedResponseExceptionInformation;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.HttpMethod;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.implementation.http.RestProxy;
import com.generic.core.implementation.http.rest.RestProxyUtils;
import com.generic.core.models.BinaryData;
import com.generic.core.models.Context;

/**
 * An instance of this class provides access to all the operations defined in Embeddings.
 */
public final class EmbeddingsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final EmbeddingsService service;

    /**
     * The service client containing this operation class.
     */
    private final OpenAiClientImpl client;

    /**
     * Initializes an instance of EmbeddingsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    EmbeddingsImpl(OpenAiClientImpl client) {
        this.service = RestProxy.create(EmbeddingsService.class, client.getHttpPipeline(),
            RestProxyUtils.createDefaultSerializer());
        this.client = client;
    }

    /**
     * The interface defining all the services for OpenAiClientEmbeddings to be used by the proxy service to perform
     * REST calls.
     */
    @ServiceInterface(name = "OpenAiClientEmbeddin", host = "https://api.openai.com/v1")
    public interface EmbeddingsService {
        @HttpRequestInformation(method = HttpMethod.POST, path = "/embeddings", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> createEmbeddingSync(@HeaderParam("accept") String accept,
            @BodyParam("application/json") BinaryData embedding, RequestOptions requestOptions, Context context);
    }

    /**
     * Creates an embedding vector representing the input text.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     model: String(text-embedding-ada-002) (Required)
     *     input: BinaryData (Required)
     *     user: String (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     object: String (Required)
     *     model: String (Required)
     *     data (Required): [
     *          (Required){
     *             index: long (Required)
     *             object: String (Required)
     *             embedding (Required): [
     *                 double (Required)
     *             ]
     *         }
     *     ]
     *     usage (Required): {
     *         prompt_tokens: long (Required)
     *         total_tokens: long (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param embedding The embedding parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createEmbeddingWithResponse(BinaryData embedding, RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.createEmbeddingSync(accept, embedding, requestOptions, Context.NONE);
    }
}
