// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.implementation;

import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceInterface;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.annotation.BodyParam;
import com.generic.core.http.annotation.HeaderParam;
import com.generic.core.http.annotation.HttpRequestInformation;
import com.generic.core.http.annotation.PathParam;
import com.generic.core.http.annotation.UnexpectedResponseExceptionInformation;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.HttpMethod;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.implementation.http.RestProxy;
import com.generic.core.implementation.http.rest.RestProxyUtils;
import com.generic.core.models.BinaryData;
import com.generic.core.models.Context;

/**
 * An instance of this class provides access to all the operations defined in FineTuningJobs.
 */
public final class FineTuningJobsImpl {
    /**
     * The proxy service used to perform REST calls.
     */
    private final FineTuningJobsService service;

    /**
     * The service client containing this operation class.
     */
    private final OpenAiClientImpl client;

    /**
     * Initializes an instance of FineTuningJobsImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    FineTuningJobsImpl(OpenAiClientImpl client) {
        this.service = RestProxy.create(FineTuningJobsService.class, client.getHttpPipeline(),
            RestProxyUtils.createDefaultSerializer());
        this.client = client;
    }

    /**
     * The interface defining all the services for OpenAiClientFineTuningJobs to be used by the proxy service to
     * perform REST calls.
     */
    @ServiceInterface(name = "OpenAiClientFineTuni", host = "https://api.openai.com/v1")
    public interface FineTuningJobsService {
        @HttpRequestInformation(method = HttpMethod.POST, path = "/fine_tuning/jobs", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> createFineTuningJobSync(@HeaderParam("accept") String accept,
            @BodyParam("application/json") BinaryData job, RequestOptions requestOptions, Context context);

        @HttpRequestInformation(method = HttpMethod.GET, path = "/fine_tuning/jobs", expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> listPaginatedFineTuningJobsSync(@HeaderParam("accept") String accept,
            RequestOptions requestOptions, Context context);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/fine_tuning/jobs/{fine_tuning_job_id}",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> retrieveFineTuningJobSync(@PathParam("fine_tuning_job_id") String fineTuningJobId,
            @HeaderParam("accept") String accept, RequestOptions requestOptions, Context context);

        @HttpRequestInformation(
            method = HttpMethod.GET,
            path = "/fine_tuning/jobs/{fine_tuning_job_id}/events",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> listFineTuningEventsSync(@PathParam("fine_tuning_job_id") String fineTuningJobId,
            @HeaderParam("accept") String accept, RequestOptions requestOptions, Context context);

        @HttpRequestInformation(
            method = HttpMethod.POST,
            path = "/fine_tuning/jobs/{fine_tuning_job_id}/cancel",
            expectedStatusCodes = { 200 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_MODIFIED", statusCode = { 409 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "RESOURCE_NOT_FOUND", statusCode = { 404 })
        @UnexpectedResponseExceptionInformation(exceptionTypeName = "CLIENT_AUTHENTICATION", statusCode = { 401 })
        @UnexpectedResponseExceptionInformation
        Response<BinaryData> cancelFineTuningJobSync(@PathParam("fine_tuning_job_id") String fineTuningJobId,
            @HeaderParam("accept") String accept, RequestOptions requestOptions, Context context);
    }

    /**
     * Creates a job that fine-tunes a specified model from a given dataset.
     * 
     * Response includes details of the enqueued job including job status and the name of the
     * fine-tuned models once complete.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     training_file: String (Required)
     *     validation_file: String (Optional)
     *     model: String(babbage-002/davinci-002/gpt-3.5-turbo) (Required)
     *     hyperparameters (Optional): {
     *         n_epochs: BinaryData (Optional)
     *     }
     *     suffix: String (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created_at: long (Required)
     *     finished_at: OffsetDateTime (Required)
     *     model: String (Required)
     *     fine_tuned_model: String (Required)
     *     organization_id: String (Required)
     *     status: String(created/pending/running/succeeded/failed/cancelled) (Required)
     *     hyperparameters (Required): {
     *         n_epochs: BinaryData (Optional)
     *     }
     *     training_file: String (Required)
     *     validation_file: String (Required)
     *     result_files (Required): [
     *         String (Required)
     *     ]
     *     trained_tokens: Long (Required)
     *     error (Required): {
     *         message: String (Optional)
     *         code: String (Optional)
     *         param: String (Optional)
     *     }
     * }
     * }</pre>
     * 
     * @param job The job parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createFineTuningJobWithResponse(BinaryData job, RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.createFineTuningJobSync(accept, job, requestOptions, Context.NONE);
    }

    /**
     * The listPaginatedFineTuningJobs operation.
     * <p>
     * <strong>Query Parameters</strong>
     * </p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr>
     * <th>Name</th>
     * <th>Type</th>
     * <th>Required</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td>after</td>
     * <td>String</td>
     * <td>No</td>
     * <td>Identifier for the last job from the previous pagination request.</td>
     * </tr>
     * <tr>
     * <td>limit</td>
     * <td>Long</td>
     * <td>No</td>
     * <td>Number of fine-tuning jobs to retrieve.</td>
     * </tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     object: String (Required)
     *     data (Required): [
     *          (Required){
     *             id: String (Required)
     *             object: String (Required)
     *             created_at: long (Required)
     *             finished_at: OffsetDateTime (Required)
     *             model: String (Required)
     *             fine_tuned_model: String (Required)
     *             organization_id: String (Required)
     *             status: String(created/pending/running/succeeded/failed/cancelled) (Required)
     *             hyperparameters (Required): {
     *                 n_epochs: BinaryData (Optional)
     *             }
     *             training_file: String (Required)
     *             validation_file: String (Required)
     *             result_files (Required): [
     *                 String (Required)
     *             ]
     *             trained_tokens: Long (Required)
     *             error (Required): {
     *                 message: String (Optional)
     *                 code: String (Optional)
     *                 param: String (Optional)
     *             }
     *         }
     *     ]
     *     has_more: boolean (Required)
     * }
     * }</pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listPaginatedFineTuningJobsWithResponse(RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.listPaginatedFineTuningJobsSync(accept, requestOptions, Context.NONE);
    }

    /**
     * Get info about a fine-tuning job.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created_at: long (Required)
     *     finished_at: OffsetDateTime (Required)
     *     model: String (Required)
     *     fine_tuned_model: String (Required)
     *     organization_id: String (Required)
     *     status: String(created/pending/running/succeeded/failed/cancelled) (Required)
     *     hyperparameters (Required): {
     *         n_epochs: BinaryData (Optional)
     *     }
     *     training_file: String (Required)
     *     validation_file: String (Required)
     *     result_files (Required): [
     *         String (Required)
     *     ]
     *     trained_tokens: Long (Required)
     *     error (Required): {
     *         message: String (Optional)
     *         code: String (Optional)
     *         param: String (Optional)
     *     }
     * }
     * }</pre>
     * 
     * @param fineTuningJobId A sequence of textual characters.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> retrieveFineTuningJobWithResponse(String fineTuningJobId,
        RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.retrieveFineTuningJobSync(fineTuningJobId, accept, requestOptions, Context.NONE);
    }

    /**
     * Get status updates for a fine-tuning job.
     * <p>
     * <strong>Query Parameters</strong>
     * </p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr>
     * <th>Name</th>
     * <th>Type</th>
     * <th>Required</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td>after</td>
     * <td>String</td>
     * <td>No</td>
     * <td>Identifier for the last event from the previous pagination request.</td>
     * </tr>
     * <tr>
     * <td>limit</td>
     * <td>Integer</td>
     * <td>No</td>
     * <td>Number of events to retrieve.</td>
     * </tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     object: String (Required)
     *     data (Required): [
     *          (Required){
     *             id: String (Required)
     *             object: String (Required)
     *             created_at: long (Required)
     *             level: String(info/warn/error) (Required)
     *             message: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get events for.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listFineTuningEventsWithResponse(String fineTuningJobId,
        RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.listFineTuningEventsSync(fineTuningJobId, accept, requestOptions, Context.NONE);
    }

    /**
     * Immediately cancel a fine-tune job.
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created_at: long (Required)
     *     finished_at: OffsetDateTime (Required)
     *     model: String (Required)
     *     fine_tuned_model: String (Required)
     *     organization_id: String (Required)
     *     status: String(created/pending/running/succeeded/failed/cancelled) (Required)
     *     hyperparameters (Required): {
     *         n_epochs: BinaryData (Optional)
     *     }
     *     training_file: String (Required)
     *     validation_file: String (Required)
     *     result_files (Required): [
     *         String (Required)
     *     ]
     *     trained_tokens: Long (Required)
     *     error (Required): {
     *         message: String (Optional)
     *         code: String (Optional)
     *         param: String (Optional)
     *     }
     * }
     * }</pre>
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to cancel.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> cancelFineTuningJobWithResponse(String fineTuningJobId, RequestOptions requestOptions) {
        final String accept = "application/json";
        return service.cancelFineTuningJobSync(fineTuningJobId, accept, requestOptions, Context.NONE);
    }
}
