// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob;

import com.azure.storage.blob.implementation.ContainerBlobPageBlobsImpl;
import com.azure.storage.blob.models.EncryptionAlgorithmType;
import com.azure.storage.blob.models.FileShareTokenIntent;
import com.azure.storage.blob.models.ImmutabilityPolicyMode;
import com.azure.storage.blob.models.PageList;
import com.azure.storage.blob.models.PremiumPageBlobAccessTier;
import com.azure.storage.blob.models.SequenceNumberActionType;
import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.annotations.ReturnType;
import io.clientcore.core.annotations.ServiceClient;
import io.clientcore.core.annotations.ServiceMethod;
import io.clientcore.core.http.models.HttpRequestConditions;
import io.clientcore.core.http.models.HttpResponseException;
import io.clientcore.core.http.models.RequestContext;
import io.clientcore.core.http.models.Response;
import io.clientcore.core.instrumentation.Instrumentation;
import io.clientcore.core.models.binarydata.BinaryData;
import java.time.OffsetDateTime;

/**
 * Initializes a new instance of the synchronous BlobClient type.
 */
@ServiceClient(builder = BlobClientBuilder.class)
public final class ContainerBlobPageBlobClient {
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final ContainerBlobPageBlobsImpl serviceClient;

    private final Instrumentation instrumentation;

    /**
     * Initializes an instance of ContainerBlobPageBlobClient class.
     * 
     * @param serviceClient the service client implementation.
     * @param instrumentation the instrumentation instance.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    ContainerBlobPageBlobClient(ContainerBlobPageBlobsImpl serviceClient, Instrumentation instrumentation) {
        this.serviceClient = serviceClient;
        this.instrumentation = instrumentation;
    }

    /**
     * The Create operation creates a new page blob.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @param metadata The metadata headers.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param tier Optional. Indicates the tier to be set on the page blob.
     * @param blobContentType Optional. Sets the blob's content type. If specified, this property is stored with the
     * blob and returned with a read request.
     * @param blobContentEncoding Optional. Sets the blob's content encoding. If specified, this property is stored with
     * the blob and returned with a read request.
     * @param blobContentLanguage Optional. Set the blob's content language. If specified, this property is stored with
     * the blob and returned with a read request.
     * @param blobContentMd5 Optional. An MD5 hash of the blob content. Note that this hash is not validated, as the
     * hashes for the individual blocks were validated when each was uploaded.
     * @param blobCacheControl Optional. Sets the blob's cache control. If specified, this property is stored with the
     * blob and returned with a read request.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param blobContentDisposition Optional. Sets the blob's content disposition. If specified, this property is
     * stored with the blob and returned with a read request.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param blobSequenceNumber Set for page blobs only. The sequence number is a user-controlled value that you can
     * use to track requests. The value of the sequence number must be between 0 and 2^63 - 1.
     * @param blobTagsString Optional. Used to set blob tags in various blob operations.
     * @param immutabilityPolicyExpiry Specifies the date time when the blobs immutability policy is set to expire.
     * @param immutabilityPolicyMode Specifies the immutability policy mode to set on the blob.
     * @param legalHold Specified if a legal hold should be set on the blob.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> createWithResponse(long blobContentLength, String metadata, Integer timeout,
        PremiumPageBlobAccessTier tier, String blobContentType, String blobContentEncoding, String blobContentLanguage,
        byte[] blobContentMd5, String blobCacheControl, String leaseId, String blobContentDisposition,
        String encryptionKey, String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm,
        String encryptionScope, String ifTags, Long blobSequenceNumber, String blobTagsString,
        OffsetDateTime immutabilityPolicyExpiry, ImmutabilityPolicyMode immutabilityPolicyMode, Boolean legalHold,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.create",
            requestContext,
            updatedContext -> this.serviceClient.createWithResponse(blobContentLength, metadata, timeout, tier,
                blobContentType, blobContentEncoding, blobContentLanguage, blobContentMd5, blobCacheControl, leaseId,
                blobContentDisposition, encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
                ifTags, blobSequenceNumber, blobTagsString, immutabilityPolicyExpiry, immutabilityPolicyMode, legalHold,
                requestConditions, updatedContext));
    }

    /**
     * The Create operation creates a new page blob.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @param metadata The metadata headers.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param tier Optional. Indicates the tier to be set on the page blob.
     * @param blobContentType Optional. Sets the blob's content type. If specified, this property is stored with the
     * blob and returned with a read request.
     * @param blobContentEncoding Optional. Sets the blob's content encoding. If specified, this property is stored with
     * the blob and returned with a read request.
     * @param blobContentLanguage Optional. Set the blob's content language. If specified, this property is stored with
     * the blob and returned with a read request.
     * @param blobContentMd5 Optional. An MD5 hash of the blob content. Note that this hash is not validated, as the
     * hashes for the individual blocks were validated when each was uploaded.
     * @param blobCacheControl Optional. Sets the blob's cache control. If specified, this property is stored with the
     * blob and returned with a read request.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param blobContentDisposition Optional. Sets the blob's content disposition. If specified, this property is
     * stored with the blob and returned with a read request.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param blobSequenceNumber Set for page blobs only. The sequence number is a user-controlled value that you can
     * use to track requests. The value of the sequence number must be between 0 and 2^63 - 1.
     * @param blobTagsString Optional. Used to set blob tags in various blob operations.
     * @param immutabilityPolicyExpiry Specifies the date time when the blobs immutability policy is set to expire.
     * @param immutabilityPolicyMode Specifies the immutability policy mode to set on the blob.
     * @param legalHold Specified if a legal hold should be set on the blob.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void create(long blobContentLength, String metadata, Integer timeout, PremiumPageBlobAccessTier tier,
        String blobContentType, String blobContentEncoding, String blobContentLanguage, byte[] blobContentMd5,
        String blobCacheControl, String leaseId, String blobContentDisposition, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope, String ifTags,
        Long blobSequenceNumber, String blobTagsString, OffsetDateTime immutabilityPolicyExpiry,
        ImmutabilityPolicyMode immutabilityPolicyMode, Boolean legalHold, HttpRequestConditions requestConditions) {
        createWithResponse(blobContentLength, metadata, timeout, tier, blobContentType, blobContentEncoding,
            blobContentLanguage, blobContentMd5, blobCacheControl, leaseId, blobContentDisposition, encryptionKey,
            encryptionKeySha256, encryptionAlgorithm, encryptionScope, ifTags, blobSequenceNumber, blobTagsString,
            immutabilityPolicyExpiry, immutabilityPolicyMode, legalHold, requestConditions, RequestContext.none());
    }

    /**
     * The Create operation creates a new page blob.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void create(long blobContentLength) {
        final String metadata = null;
        final Integer timeout = null;
        final PremiumPageBlobAccessTier tier = null;
        final String blobContentType = null;
        final String blobContentEncoding = null;
        final String blobContentLanguage = null;
        final byte[] blobContentMd5 = null;
        final String blobCacheControl = null;
        final String leaseId = null;
        final String blobContentDisposition = null;
        final String encryptionKey = null;
        final String encryptionKeySha256 = null;
        final EncryptionAlgorithmType encryptionAlgorithm = null;
        final String encryptionScope = null;
        final String ifTags = null;
        final Long blobSequenceNumber = null;
        final String blobTagsString = null;
        final OffsetDateTime immutabilityPolicyExpiry = null;
        final ImmutabilityPolicyMode immutabilityPolicyMode = null;
        final Boolean legalHold = null;
        final HttpRequestConditions requestConditions = null;
        createWithResponse(blobContentLength, metadata, timeout, tier, blobContentType, blobContentEncoding,
            blobContentLanguage, blobContentMd5, blobCacheControl, leaseId, blobContentDisposition, encryptionKey,
            encryptionKeySha256, encryptionAlgorithm, encryptionScope, ifTags, blobSequenceNumber, blobTagsString,
            immutabilityPolicyExpiry, immutabilityPolicyMode, legalHold, requestConditions, RequestContext.none());
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob.
     * 
     * @param contentLength The length of the request.
     * @param range Bytes of data in the specified range.
     * @param body The body of the request.
     * @param transactionalContentMD5 Optional. An MD5 hash of the blob content. Note that this hash is not validated,
     * as the hashes for the individual blocks were validated when each was uploaded.
     * @param transactionalContentCrc64 Specify the transactional crc64 for the body, to be validated by the service.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param structuredBodyType Required if the request body is a structured message. Specifies the message schema
     * version and properties.
     * @param structuredContentLength Required if the request body is a structured message. Specifies the length of the
     * blob/file content inside the message body. Will always be smaller than Content-Length.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> uploadPagesWithResponse(long contentLength, String range, BinaryData body,
        byte[] transactionalContentMD5, byte[] transactionalContentCrc64, Integer timeout, String leaseId,
        String encryptionKey, String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm,
        String encryptionScope, Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan,
        Long ifSequenceNumberEqualTo, String ifTags, String structuredBodyType, Long structuredContentLength,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.uploadPages",
            requestContext,
            updatedContext -> this.serviceClient.uploadPagesWithResponse(contentLength, range, body,
                transactionalContentMD5, transactionalContentCrc64, timeout, leaseId, encryptionKey,
                encryptionKeySha256, encryptionAlgorithm, encryptionScope, ifSequenceNumberLessThanOrEqualTo,
                ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags, structuredBodyType, structuredContentLength,
                requestConditions, updatedContext));
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob.
     * 
     * @param contentLength The length of the request.
     * @param range Bytes of data in the specified range.
     * @param body The body of the request.
     * @param transactionalContentMD5 Optional. An MD5 hash of the blob content. Note that this hash is not validated,
     * as the hashes for the individual blocks were validated when each was uploaded.
     * @param transactionalContentCrc64 Specify the transactional crc64 for the body, to be validated by the service.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param structuredBodyType Required if the request body is a structured message. Specifies the message schema
     * version and properties.
     * @param structuredContentLength Required if the request body is a structured message. Specifies the length of the
     * blob/file content inside the message body. Will always be smaller than Content-Length.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void uploadPages(long contentLength, String range, BinaryData body, byte[] transactionalContentMD5,
        byte[] transactionalContentCrc64, Integer timeout, String leaseId, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, String structuredBodyType, Long structuredContentLength,
        HttpRequestConditions requestConditions) {
        uploadPagesWithResponse(contentLength, range, body, transactionalContentMD5, transactionalContentCrc64, timeout,
            leaseId, encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
            ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags,
            structuredBodyType, structuredContentLength, requestConditions, RequestContext.none());
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob.
     * 
     * @param contentLength The length of the request.
     * @param range Bytes of data in the specified range.
     * @param body The body of the request.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void uploadPages(long contentLength, String range, BinaryData body) {
        final byte[] transactionalContentMD5 = null;
        final byte[] transactionalContentCrc64 = null;
        final Integer timeout = null;
        final String leaseId = null;
        final String encryptionKey = null;
        final String encryptionKeySha256 = null;
        final EncryptionAlgorithmType encryptionAlgorithm = null;
        final String encryptionScope = null;
        final Long ifSequenceNumberLessThanOrEqualTo = null;
        final Long ifSequenceNumberLessThan = null;
        final Long ifSequenceNumberEqualTo = null;
        final String ifTags = null;
        final String structuredBodyType = null;
        final Long structuredContentLength = null;
        final HttpRequestConditions requestConditions = null;
        uploadPagesWithResponse(contentLength, range, body, transactionalContentMD5, transactionalContentCrc64, timeout,
            leaseId, encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
            ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags,
            structuredBodyType, structuredContentLength, requestConditions, RequestContext.none());
    }

    /**
     * The Clear Pages operation clears a range of pages from a page blob.
     * 
     * @param range Bytes of data in the specified range.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> clearPagesWithResponse(String range, Integer timeout, String leaseId, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.clearPages",
            requestContext,
            updatedContext -> this.serviceClient.clearPagesWithResponse(range, timeout, leaseId, encryptionKey,
                encryptionKeySha256, encryptionAlgorithm, encryptionScope, ifSequenceNumberLessThanOrEqualTo,
                ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags, requestConditions, updatedContext));
    }

    /**
     * The Clear Pages operation clears a range of pages from a page blob.
     * 
     * @param range Bytes of data in the specified range.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void clearPages(String range, Integer timeout, String leaseId, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, HttpRequestConditions requestConditions) {
        clearPagesWithResponse(range, timeout, leaseId, encryptionKey, encryptionKeySha256, encryptionAlgorithm,
            encryptionScope, ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo,
            ifTags, requestConditions, RequestContext.none());
    }

    /**
     * The Clear Pages operation clears a range of pages from a page blob.
     * 
     * @param range Bytes of data in the specified range.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void clearPages(String range) {
        final Integer timeout = null;
        final String leaseId = null;
        final String encryptionKey = null;
        final String encryptionKeySha256 = null;
        final EncryptionAlgorithmType encryptionAlgorithm = null;
        final String encryptionScope = null;
        final Long ifSequenceNumberLessThanOrEqualTo = null;
        final Long ifSequenceNumberLessThan = null;
        final Long ifSequenceNumberEqualTo = null;
        final String ifTags = null;
        final HttpRequestConditions requestConditions = null;
        clearPagesWithResponse(range, timeout, leaseId, encryptionKey, encryptionKeySha256, encryptionAlgorithm,
            encryptionScope, ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo,
            ifTags, requestConditions, RequestContext.none());
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob where the contents are read from a URL.
     * 
     * @param sourceUrl Specify a URL to the copy source.
     * @param sourceRange Bytes of source data in the specified range. The length of this range should match the
     * ContentLength header and x-ms-range/Range destination range header.
     * @param contentLength The length of the request.
     * @param range Bytes of source data in the specified range. The length of this range should match the ContentLength
     * header and x-ms-range/Range destination range header.
     * @param sourceContentMd5 Specify the md5 calculated for the range of bytes that must be read from the copy source.
     * @param sourceContentCrc64 Specify the crc64 calculated for the range of bytes that must be read from the copy
     * source.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param sourceIfModifiedSince Specify this header value to operate only on a blob if it has been modified since
     * the specified date/time.
     * @param sourceIfUnmodifiedSince Specify this header value to operate only on a blob if it has not been modified
     * since the specified date/time.
     * @param sourceIfMatch Specify an ETag value to operate only on blobs with a matching value.
     * @param sourceIfNoneMatch Specify this header value to operate only on a blob if it has been modified since the
     * specified date/time.
     * @param copySourceAuthorization Only Bearer type is supported. Credentials should be a valid OAuth access token to
     * copy source.
     * @param fileRequestIntent Valid value is backup.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> uploadPagesFromUrlWithResponse(String sourceUrl, String sourceRange, long contentLength,
        String range, byte[] sourceContentMd5, byte[] sourceContentCrc64, Integer timeout, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope, String leaseId,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, OffsetDateTime sourceIfModifiedSince, OffsetDateTime sourceIfUnmodifiedSince,
        String sourceIfMatch, String sourceIfNoneMatch, String copySourceAuthorization,
        FileShareTokenIntent fileRequestIntent, HttpRequestConditions requestConditions,
        RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.uploadPagesFromUrl",
            requestContext,
            updatedContext -> this.serviceClient.uploadPagesFromUrlWithResponse(sourceUrl, sourceRange, contentLength,
                range, sourceContentMd5, sourceContentCrc64, timeout, encryptionKey, encryptionKeySha256,
                encryptionAlgorithm, encryptionScope, leaseId, ifSequenceNumberLessThanOrEqualTo,
                ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags, sourceIfModifiedSince,
                sourceIfUnmodifiedSince, sourceIfMatch, sourceIfNoneMatch, copySourceAuthorization, fileRequestIntent,
                requestConditions, updatedContext));
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob where the contents are read from a URL.
     * 
     * @param sourceUrl Specify a URL to the copy source.
     * @param sourceRange Bytes of source data in the specified range. The length of this range should match the
     * ContentLength header and x-ms-range/Range destination range header.
     * @param contentLength The length of the request.
     * @param range Bytes of source data in the specified range. The length of this range should match the ContentLength
     * header and x-ms-range/Range destination range header.
     * @param sourceContentMd5 Specify the md5 calculated for the range of bytes that must be read from the copy source.
     * @param sourceContentCrc64 Specify the crc64 calculated for the range of bytes that must be read from the copy
     * source.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifSequenceNumberLessThanOrEqualTo Specify this header value to operate only on a blob if it has a sequence
     * number less than or equal to the specified.
     * @param ifSequenceNumberLessThan Specify this header value to operate only on a blob if it has a sequence number
     * less than the specified.
     * @param ifSequenceNumberEqualTo Specify this header value to operate only on a blob if it has the specified
     * sequence number.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param sourceIfModifiedSince Specify this header value to operate only on a blob if it has been modified since
     * the specified date/time.
     * @param sourceIfUnmodifiedSince Specify this header value to operate only on a blob if it has not been modified
     * since the specified date/time.
     * @param sourceIfMatch Specify an ETag value to operate only on blobs with a matching value.
     * @param sourceIfNoneMatch Specify this header value to operate only on a blob if it has been modified since the
     * specified date/time.
     * @param copySourceAuthorization Only Bearer type is supported. Credentials should be a valid OAuth access token to
     * copy source.
     * @param fileRequestIntent Valid value is backup.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void uploadPagesFromUrl(String sourceUrl, String sourceRange, long contentLength, String range,
        byte[] sourceContentMd5, byte[] sourceContentCrc64, Integer timeout, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope, String leaseId,
        Long ifSequenceNumberLessThanOrEqualTo, Long ifSequenceNumberLessThan, Long ifSequenceNumberEqualTo,
        String ifTags, OffsetDateTime sourceIfModifiedSince, OffsetDateTime sourceIfUnmodifiedSince,
        String sourceIfMatch, String sourceIfNoneMatch, String copySourceAuthorization,
        FileShareTokenIntent fileRequestIntent, HttpRequestConditions requestConditions) {
        uploadPagesFromUrlWithResponse(sourceUrl, sourceRange, contentLength, range, sourceContentMd5,
            sourceContentCrc64, timeout, encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
            leaseId, ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags,
            sourceIfModifiedSince, sourceIfUnmodifiedSince, sourceIfMatch, sourceIfNoneMatch, copySourceAuthorization,
            fileRequestIntent, requestConditions, RequestContext.none());
    }

    /**
     * The Upload Pages operation writes a range of pages to a page blob where the contents are read from a URL.
     * 
     * @param sourceUrl Specify a URL to the copy source.
     * @param sourceRange Bytes of source data in the specified range. The length of this range should match the
     * ContentLength header and x-ms-range/Range destination range header.
     * @param contentLength The length of the request.
     * @param range Bytes of source data in the specified range. The length of this range should match the ContentLength
     * header and x-ms-range/Range destination range header.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void uploadPagesFromUrl(String sourceUrl, String sourceRange, long contentLength, String range) {
        final byte[] sourceContentMd5 = null;
        final byte[] sourceContentCrc64 = null;
        final Integer timeout = null;
        final String encryptionKey = null;
        final String encryptionKeySha256 = null;
        final EncryptionAlgorithmType encryptionAlgorithm = null;
        final String encryptionScope = null;
        final String leaseId = null;
        final Long ifSequenceNumberLessThanOrEqualTo = null;
        final Long ifSequenceNumberLessThan = null;
        final Long ifSequenceNumberEqualTo = null;
        final String ifTags = null;
        final OffsetDateTime sourceIfModifiedSince = null;
        final OffsetDateTime sourceIfUnmodifiedSince = null;
        final String sourceIfMatch = null;
        final String sourceIfNoneMatch = null;
        final String copySourceAuthorization = null;
        final FileShareTokenIntent fileRequestIntent = null;
        final HttpRequestConditions requestConditions = null;
        uploadPagesFromUrlWithResponse(sourceUrl, sourceRange, contentLength, range, sourceContentMd5,
            sourceContentCrc64, timeout, encryptionKey, encryptionKeySha256, encryptionAlgorithm, encryptionScope,
            leaseId, ifSequenceNumberLessThanOrEqualTo, ifSequenceNumberLessThan, ifSequenceNumberEqualTo, ifTags,
            sourceIfModifiedSince, sourceIfUnmodifiedSince, sourceIfMatch, sourceIfNoneMatch, copySourceAuthorization,
            fileRequestIntent, requestConditions, RequestContext.none());
    }

    /**
     * The Get Page Ranges operation returns the list of valid page ranges for a page blob or snapshot of a page blob.
     * 
     * @param snapshot The snapshot parameter is an opaque DateTime value that, when present, specifies the blob
     * snapshot to retrieve. For more information on working with blob snapshots, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating
     * a Snapshot of a Blob.&lt;/a&gt;.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param range Return only the bytes of the blob in the specified range.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param marker A string value that identifies the portion of the list of containers to be returned with the next
     * listing operation. The operation returns the NextMarker value within the response body if the listing operation
     * did not return all containers remaining to be listed with the current page. The NextMarker value can be used as
     * the value for the marker parameter in a subsequent call to request the next page of list items. The marker value
     * is opaque to the client.
     * @param maxresults Specifies the maximum number of containers to return. If the request does not specify
     * maxresults, or specifies a value greater than 5000, the server will return up to 5000 items.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<PageList> getPageRangesWithResponse(String snapshot, Integer timeout, String range, String leaseId,
        String ifTags, String marker, Integer maxresults, HttpRequestConditions requestConditions,
        RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.getPageRanges",
            requestContext, updatedContext -> this.serviceClient.getPageRangesWithResponse(snapshot, timeout, range,
                leaseId, ifTags, marker, maxresults, requestConditions, updatedContext));
    }

    /**
     * The Get Page Ranges operation returns the list of valid page ranges for a page blob or snapshot of a page blob.
     * 
     * @param snapshot The snapshot parameter is an opaque DateTime value that, when present, specifies the blob
     * snapshot to retrieve. For more information on working with blob snapshots, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating
     * a Snapshot of a Blob.&lt;/a&gt;.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param range Return only the bytes of the blob in the specified range.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param marker A string value that identifies the portion of the list of containers to be returned with the next
     * listing operation. The operation returns the NextMarker value within the response body if the listing operation
     * did not return all containers remaining to be listed with the current page. The NextMarker value can be used as
     * the value for the marker parameter in a subsequent call to request the next page of list items. The marker value
     * is opaque to the client.
     * @param maxresults Specifies the maximum number of containers to return. If the request does not specify
     * maxresults, or specifies a value greater than 5000, the server will return up to 5000 items.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public PageList getPageRanges(String snapshot, Integer timeout, String range, String leaseId, String ifTags,
        String marker, Integer maxresults, HttpRequestConditions requestConditions) {
        return getPageRangesWithResponse(snapshot, timeout, range, leaseId, ifTags, marker, maxresults,
            requestConditions, RequestContext.none()).getValue();
    }

    /**
     * The Get Page Ranges operation returns the list of valid page ranges for a page blob or snapshot of a page blob.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public PageList getPageRanges() {
        final String snapshot = null;
        final Integer timeout = null;
        final String range = null;
        final String leaseId = null;
        final String ifTags = null;
        final String marker = null;
        final Integer maxresults = null;
        final HttpRequestConditions requestConditions = null;
        return getPageRangesWithResponse(snapshot, timeout, range, leaseId, ifTags, marker, maxresults,
            requestConditions, RequestContext.none()).getValue();
    }

    /**
     * The Get Page Ranges Diff operation returns the list of valid page ranges for a page blob or snapshot of a page
     * blob.
     * 
     * @param snapshot The snapshot parameter is an opaque DateTime value that, when present, specifies the blob
     * snapshot to retrieve. For more information on working with blob snapshots, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating
     * a Snapshot of a Blob.&lt;/a&gt;.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param prevsnapshot Optional in version 2015-07-08 and newer. The prevsnapshot parameter is a DateTime value that
     * specifies that the response will contain only pages that were changed between target blob and previous snapshot.
     * Changed pages include both updated and cleared pages. The target blob may be a snapshot, as long as the snapshot
     * specified by prevsnapshot is the older of the two. Note that incremental snapshots are currently supported only
     * for blobs created on or after January 1, 2016.
     * @param prevSnapshotUrl Optional. This header is only supported in service versions 2019-04-19 and after and
     * specifies the URL of a previous snapshot of the target blob. The response will only contain pages that were
     * changed between the target blob and its previous snapshot.
     * @param range Return only the bytes of the blob in the specified range.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param marker A string value that identifies the portion of the list of containers to be returned with the next
     * listing operation. The operation returns the NextMarker value within the response body if the listing operation
     * did not return all containers remaining to be listed with the current page. The NextMarker value can be used as
     * the value for the marker parameter in a subsequent call to request the next page of list items. The marker value
     * is opaque to the client.
     * @param maxresults Specifies the maximum number of containers to return. If the request does not specify
     * maxresults, or specifies a value greater than 5000, the server will return up to 5000 items.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<PageList> getPageRangesDiffWithResponse(String snapshot, Integer timeout, String prevsnapshot,
        String prevSnapshotUrl, String range, String leaseId, String ifTags, String marker, Integer maxresults,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.getPageRangesDiff",
            requestContext,
            updatedContext -> this.serviceClient.getPageRangesDiffWithResponse(snapshot, timeout, prevsnapshot,
                prevSnapshotUrl, range, leaseId, ifTags, marker, maxresults, requestConditions, updatedContext));
    }

    /**
     * The Get Page Ranges Diff operation returns the list of valid page ranges for a page blob or snapshot of a page
     * blob.
     * 
     * @param snapshot The snapshot parameter is an opaque DateTime value that, when present, specifies the blob
     * snapshot to retrieve. For more information on working with blob snapshots, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/creating-a-snapshot-of-a-blob"&gt;Creating
     * a Snapshot of a Blob.&lt;/a&gt;.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param prevsnapshot Optional in version 2015-07-08 and newer. The prevsnapshot parameter is a DateTime value that
     * specifies that the response will contain only pages that were changed between target blob and previous snapshot.
     * Changed pages include both updated and cleared pages. The target blob may be a snapshot, as long as the snapshot
     * specified by prevsnapshot is the older of the two. Note that incremental snapshots are currently supported only
     * for blobs created on or after January 1, 2016.
     * @param prevSnapshotUrl Optional. This header is only supported in service versions 2019-04-19 and after and
     * specifies the URL of a previous snapshot of the target blob. The response will only contain pages that were
     * changed between the target blob and its previous snapshot.
     * @param range Return only the bytes of the blob in the specified range.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param marker A string value that identifies the portion of the list of containers to be returned with the next
     * listing operation. The operation returns the NextMarker value within the response body if the listing operation
     * did not return all containers remaining to be listed with the current page. The NextMarker value can be used as
     * the value for the marker parameter in a subsequent call to request the next page of list items. The marker value
     * is opaque to the client.
     * @param maxresults Specifies the maximum number of containers to return. If the request does not specify
     * maxresults, or specifies a value greater than 5000, the server will return up to 5000 items.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public PageList getPageRangesDiff(String snapshot, Integer timeout, String prevsnapshot, String prevSnapshotUrl,
        String range, String leaseId, String ifTags, String marker, Integer maxresults,
        HttpRequestConditions requestConditions) {
        return getPageRangesDiffWithResponse(snapshot, timeout, prevsnapshot, prevSnapshotUrl, range, leaseId, ifTags,
            marker, maxresults, requestConditions, RequestContext.none()).getValue();
    }

    /**
     * The Get Page Ranges Diff operation returns the list of valid page ranges for a page blob or snapshot of a page
     * blob.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a page list.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public PageList getPageRangesDiff() {
        final String snapshot = null;
        final Integer timeout = null;
        final String prevsnapshot = null;
        final String prevSnapshotUrl = null;
        final String range = null;
        final String leaseId = null;
        final String ifTags = null;
        final String marker = null;
        final Integer maxresults = null;
        final HttpRequestConditions requestConditions = null;
        return getPageRangesDiffWithResponse(snapshot, timeout, prevsnapshot, prevSnapshotUrl, range, leaseId, ifTags,
            marker, maxresults, requestConditions, RequestContext.none()).getValue();
    }

    /**
     * The Resize operation increases the size of the page blob to the specified size.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> resizeWithResponse(long blobContentLength, Integer timeout, String leaseId,
        String encryptionKey, String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm,
        String encryptionScope, String ifTags, HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.resize",
            requestContext,
            updatedContext -> this.serviceClient.resizeWithResponse(blobContentLength, timeout, leaseId, encryptionKey,
                encryptionKeySha256, encryptionAlgorithm, encryptionScope, ifTags, requestConditions, updatedContext));
    }

    /**
     * The Resize operation increases the size of the page blob to the specified size.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param encryptionKey Optional. Version 2019-07-07 and later. Specifies the encryption key to use to encrypt the
     * data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param encryptionKeySha256 Optional. Version 2019-07-07 and later. Specifies the SHA256 hash of the encryption
     * key used to encrypt the data provided in the request. This header is only used for encryption with a
     * customer-provided key. If the request is authenticated with a client token, this header should be specified using
     * the SHA256 hash of the encryption key.
     * @param encryptionAlgorithm Optional. Version 2019-07-07 and later. Specifies the algorithm to use for encryption.
     * If not specified, the default is AES256.
     * @param encryptionScope Optional. Version 2019-07-07 and later. Specifies the encryption scope to use to encrypt
     * the data provided in the request. If not specified, the request will be encrypted with the root account key.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void resize(long blobContentLength, Integer timeout, String leaseId, String encryptionKey,
        String encryptionKeySha256, EncryptionAlgorithmType encryptionAlgorithm, String encryptionScope, String ifTags,
        HttpRequestConditions requestConditions) {
        resizeWithResponse(blobContentLength, timeout, leaseId, encryptionKey, encryptionKeySha256, encryptionAlgorithm,
            encryptionScope, ifTags, requestConditions, RequestContext.none());
    }

    /**
     * The Resize operation increases the size of the page blob to the specified size.
     * 
     * @param blobContentLength This header specifies the maximum size for the page blob, up to 1 TB. The page blob size
     * must be aligned to a 512-byte boundary.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void resize(long blobContentLength) {
        final Integer timeout = null;
        final String leaseId = null;
        final String encryptionKey = null;
        final String encryptionKeySha256 = null;
        final EncryptionAlgorithmType encryptionAlgorithm = null;
        final String encryptionScope = null;
        final String ifTags = null;
        final HttpRequestConditions requestConditions = null;
        resizeWithResponse(blobContentLength, timeout, leaseId, encryptionKey, encryptionKeySha256, encryptionAlgorithm,
            encryptionScope, ifTags, requestConditions, RequestContext.none());
    }

    /**
     * The Update Sequence Number operation sets the blob's sequence number. The operation will fail if the specified
     * sequence number is less than the current sequence number of the blob.
     * 
     * @param sequenceNumberAction Required if the x-ms-blob-sequence-number header is set for the request. This
     * property applies to page blobs only. This property indicates how the service should modify the blob's sequence
     * number.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param blobSequenceNumber Set for page blobs only. The sequence number is a user-controlled value that you can
     * use to track requests. The value of the sequence number must be between 0 and 2^63 - 1.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> updateSequenceNumberWithResponse(SequenceNumberActionType sequenceNumberAction,
        Integer timeout, String leaseId, String ifTags, Long blobSequenceNumber,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.updateSequenceNumber",
            requestContext, updatedContext -> this.serviceClient.updateSequenceNumberWithResponse(sequenceNumberAction,
                timeout, leaseId, ifTags, blobSequenceNumber, requestConditions, updatedContext));
    }

    /**
     * The Update Sequence Number operation sets the blob's sequence number. The operation will fail if the specified
     * sequence number is less than the current sequence number of the blob.
     * 
     * @param sequenceNumberAction Required if the x-ms-blob-sequence-number header is set for the request. This
     * property applies to page blobs only. This property indicates how the service should modify the blob's sequence
     * number.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param leaseId If specified, the operation only succeeds if the resource's lease is active and matches this ID.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param blobSequenceNumber Set for page blobs only. The sequence number is a user-controlled value that you can
     * use to track requests. The value of the sequence number must be between 0 and 2^63 - 1.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void updateSequenceNumber(SequenceNumberActionType sequenceNumberAction, Integer timeout, String leaseId,
        String ifTags, Long blobSequenceNumber, HttpRequestConditions requestConditions) {
        updateSequenceNumberWithResponse(sequenceNumberAction, timeout, leaseId, ifTags, blobSequenceNumber,
            requestConditions, RequestContext.none());
    }

    /**
     * The Update Sequence Number operation sets the blob's sequence number. The operation will fail if the specified
     * sequence number is less than the current sequence number of the blob.
     * 
     * @param sequenceNumberAction Required if the x-ms-blob-sequence-number header is set for the request. This
     * property applies to page blobs only. This property indicates how the service should modify the blob's sequence
     * number.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void updateSequenceNumber(SequenceNumberActionType sequenceNumberAction) {
        final Integer timeout = null;
        final String leaseId = null;
        final String ifTags = null;
        final Long blobSequenceNumber = null;
        final HttpRequestConditions requestConditions = null;
        updateSequenceNumberWithResponse(sequenceNumberAction, timeout, leaseId, ifTags, blobSequenceNumber,
            requestConditions, RequestContext.none());
    }

    /**
     * The Copy Incremental operation copies a snapshot of the source page blob to a destination page blob. The snapshot
     * is copied such that only the differential changes between the previously copied snapshot are transferred to the
     * destination. The copied snapshots are complete copies of the original snapshot and can be read or copied from as
     * usual. This API is supported since REST version 2016-05-31.
     * 
     * @param copySource Specifies the name of the source page blob snapshot. This value is a URL of up to 2 KB in
     * length that specifies a page blob snapshot. The value should be URL-encoded as it would appear in a request URI.
     * The source blob must either be public or must be authenticated via a shared access signature.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @param requestContext The context to configure the HTTP request before HTTP client sends it.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> copyIncrementalWithResponse(String copySource, Integer timeout, String ifTags,
        HttpRequestConditions requestConditions, RequestContext requestContext) {
        return this.instrumentation.instrumentWithResponse("Storage.Blob.Container.Blob.PageBlob.copyIncremental",
            requestContext, updatedContext -> this.serviceClient.copyIncrementalWithResponse(copySource, timeout,
                ifTags, requestConditions, updatedContext));
    }

    /**
     * The Copy Incremental operation copies a snapshot of the source page blob to a destination page blob. The snapshot
     * is copied such that only the differential changes between the previously copied snapshot are transferred to the
     * destination. The copied snapshots are complete copies of the original snapshot and can be read or copied from as
     * usual. This API is supported since REST version 2016-05-31.
     * 
     * @param copySource Specifies the name of the source page blob snapshot. This value is a URL of up to 2 KB in
     * length that specifies a page blob snapshot. The value should be URL-encoded as it would appear in a request URI.
     * The source blob must either be public or must be authenticated via a shared access signature.
     * @param timeout The timeout parameter is expressed in seconds. For more information, see &lt;a
     * href="https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/setting-timeouts-for-blob-service-operations"&gt;Setting
     * Timeouts for Blob Service Operations.&lt;/a&gt;.
     * @param ifTags Specify a SQL where clause on blob tags to operate only on blobs with a matching value.
     * @param requestConditions Specifies HTTP options for conditional requests based on modification time.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void copyIncremental(String copySource, Integer timeout, String ifTags,
        HttpRequestConditions requestConditions) {
        copyIncrementalWithResponse(copySource, timeout, ifTags, requestConditions, RequestContext.none());
    }

    /**
     * The Copy Incremental operation copies a snapshot of the source page blob to a destination page blob. The snapshot
     * is copied such that only the differential changes between the previously copied snapshot are transferred to the
     * destination. The copied snapshots are complete copies of the original snapshot and can be read or copied from as
     * usual. This API is supported since REST version 2016-05-31.
     * 
     * @param copySource Specifies the name of the source page blob snapshot. This value is a URL of up to 2 KB in
     * length that specifies a page blob snapshot. The value should be URL-encoded as it would appear in a request URI.
     * The source blob must either be public or must be authenticated via a shared access signature.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void copyIncremental(String copySource) {
        final Integer timeout = null;
        final String ifTags = null;
        final HttpRequestConditions requestConditions = null;
        copyIncrementalWithResponse(copySource, timeout, ifTags, requestConditions, RequestContext.none());
    }
}
