// Code generated by Microsoft (R) TypeSpec Code Generator.

module com.generic.ai.openai {
    requires transitive com.generic.core;
    requires com.generic.json;

    exports com.generic.ai.openai;
    exports com.generic.ai.openai.models;

    opens com.generic.ai.openai.models to com.generic.core;
}
