// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai;

import com.generic.ai.openai.implementation.ChatCompletionsImpl;
import com.generic.ai.openai.models.CreateChatCompletionRequest;
import com.generic.ai.openai.models.CreateChatCompletionResponse;
import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceClient;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.models.BinaryData;

/**
 * Initializes a new instance of the synchronous OpenAiClient type.
 */
@ServiceClient(builder = OpenAiClientBuilder.class)
public final class ChatCompletionsClient {
    @Metadata(generated = true)
    private final ChatCompletionsImpl serviceClient;

    /**
     * Initializes an instance of ChatCompletionsClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Metadata(generated = true)
    ChatCompletionsClient(ChatCompletionsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The createChatCompletion operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     model: String(gpt4/gpt-4-0314/gpt-4-0613/gpt-4-32k/gpt-4-32k-0314/gpt-4-32k-0613/gpt-3.5-turbo/gpt-3.5-turbo-16k/gpt-3.5-turbo-0301/gpt-3.5-turbo-0613/gpt-3.5-turbo-16k-0613) (Required)
     *     messages (Required): [
     *          (Required){
     *             role: String(system/user/assistant/function) (Required)
     *             content: String (Required)
     *             name: String (Optional)
     *             function_call (Optional): {
     *                 name: String (Required)
     *                 arguments: String (Required)
     *             }
     *         }
     *     ]
     *     functions (Optional): [
     *          (Optional){
     *             name: String (Required)
     *             description: String (Optional)
     *             parameters (Required): {
     *                 String: Object (Required)
     *             }
     *         }
     *     ]
     *     function_call: BinaryData (Optional)
     *     temperature: Double (Optional)
     *     top_p: Double (Optional)
     *     n: Long (Optional)
     *     max_tokens: Long (Optional)
     *     stop: BinaryData (Optional)
     *     presence_penalty: Double (Optional)
     *     frequency_penalty: Double (Optional)
     *     logit_bias (Optional): {
     *         String: long (Required)
     *     }
     *     user: String (Optional)
     *     stream: Boolean (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created: long (Required)
     *     model: String (Required)
     *     choices (Required): [
     *          (Required){
     *             index: long (Required)
     *             message (Required): {
     *                 role: String(system/user/assistant/function) (Required)
     *                 content: String (Required)
     *                 function_call (Optional): {
     *                     name: String (Required)
     *                     arguments: String (Required)
     *                 }
     *             }
     *             finish_reason: String(stop/length/function_call/content_filter) (Required)
     *         }
     *     ]
     *     usage (Optional): {
     *         prompt_tokens: long (Required)
     *         completion_tokens: long (Required)
     *         total_tokens: long (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param createChatCompletionRequest The createChatCompletionRequest parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return represents a chat completion response returned by model, based on the provided input.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createChatCompletionWithResponse(BinaryData createChatCompletionRequest,
        RequestOptions requestOptions) {
        return this.serviceClient.createChatCompletionWithResponse(createChatCompletionRequest, requestOptions);
    }

    /**
     * The createChatCompletion operation.
     * 
     * @param createChatCompletionRequest The createChatCompletionRequest parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a chat completion response returned by model, based on the provided input.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CreateChatCompletionResponse createChatCompletion(CreateChatCompletionRequest createChatCompletionRequest) {
        // Generated convenience method for createChatCompletionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createChatCompletionWithResponse(BinaryData.fromObject(createChatCompletionRequest), requestOptions)
            .getValue().toObject(CreateChatCompletionResponse.class);
    }
}
