// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai;

import com.generic.ai.openai.implementation.CompletionsImpl;
import com.generic.ai.openai.models.CreateCompletionRequest;
import com.generic.ai.openai.models.CreateCompletionResponse;
import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceClient;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.models.BinaryData;

/**
 * Initializes a new instance of the synchronous OpenAiClient type.
 */
@ServiceClient(builder = OpenAiClientBuilder.class)
public final class CompletionsClient {
    @Metadata(generated = true)
    private final CompletionsImpl serviceClient;

    /**
     * Initializes an instance of CompletionsClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Metadata(generated = true)
    CompletionsClient(CompletionsImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * The createCompletion operation.
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     model: String(babbage-002/davinci-002/text-davinci-003/text-davinci-002/text-davinci-001/code-davinci-002/text-curie-001/text-babbage-001/text-ada-001) (Required)
     *     prompt: BinaryData (Required)
     *     suffix: String (Optional)
     *     temperature: Double (Optional)
     *     top_p: Double (Optional)
     *     n: Long (Optional)
     *     max_tokens: Long (Optional)
     *     stop: BinaryData (Optional)
     *     presence_penalty: Double (Optional)
     *     frequency_penalty: Double (Optional)
     *     logit_bias (Optional): {
     *         String: long (Required)
     *     }
     *     user: String (Optional)
     *     stream: Boolean (Optional)
     *     logprobs: Long (Optional)
     *     echo: Boolean (Optional)
     *     best_of: Long (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created: long (Required)
     *     model: String (Required)
     *     choices (Required): [
     *          (Required){
     *             index: long (Required)
     *             text: String (Required)
     *             logprobs (Required): {
     *                 tokens (Required): [
     *                     String (Required)
     *                 ]
     *                 token_logprobs (Required): [
     *                     double (Required)
     *                 ]
     *                 top_logprobs (Required): [
     *                      (Required){
     *                         String: long (Required)
     *                     }
     *                 ]
     *                 text_offset (Required): [
     *                     long (Required)
     *                 ]
     *             }
     *             finish_reason: String(stop/length/content_filter) (Required)
     *         }
     *     ]
     *     usage (Optional): {
     *         prompt_tokens: long (Required)
     *         completion_tokens: long (Required)
     *         total_tokens: long (Required)
     *     }
     * }
     * }</pre>
     * 
     * @param createCompletionRequest The createCompletionRequest parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return represents a completion response from the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createCompletionWithResponse(BinaryData createCompletionRequest,
        RequestOptions requestOptions) {
        return this.serviceClient.createCompletionWithResponse(createCompletionRequest, requestOptions);
    }

    /**
     * The createCompletion operation.
     * 
     * @param createCompletionRequest The createCompletionRequest parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return represents a completion response from the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CreateCompletionResponse createCompletion(CreateCompletionRequest createCompletionRequest) {
        // Generated convenience method for createCompletionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createCompletionWithResponse(BinaryData.fromObject(createCompletionRequest), requestOptions).getValue()
            .toObject(CreateCompletionResponse.class);
    }
}
