// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai;

import com.generic.ai.openai.implementation.FineTunesImpl;
import com.generic.ai.openai.models.CreateFineTuneRequest;
import com.generic.ai.openai.models.FineTune;
import com.generic.ai.openai.models.ListFineTuneEventsResponse;
import com.generic.ai.openai.models.ListFineTunesResponse;
import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.ReturnType;
import com.generic.core.annotation.ServiceClient;
import com.generic.core.annotation.ServiceMethod;
import com.generic.core.http.Response;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.models.BinaryData;

/**
 * Initializes a new instance of the synchronous OpenAiClient type.
 */
@ServiceClient(builder = OpenAiClientBuilder.class)
public final class FineTunesClient {
    @Metadata(generated = true)
    private final FineTunesImpl serviceClient;

    /**
     * Initializes an instance of FineTunesClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Metadata(generated = true)
    FineTunesClient(FineTunesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Creates a job that fine-tunes a specified model from a given dataset.
     * 
     * Response includes details of the enqueued job including job status and the name of the fine-tuned models once
     * complete.
     * 
     * [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning).
     * <p>
     * <strong>Request Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     training_file: String (Required)
     *     validation_file: String (Optional)
     *     model: String(ada/babbage/curie/davinci) (Optional)
     *     n_epochs: Long (Optional)
     *     batch_size: Long (Optional)
     *     learning_rate_multiplier: Double (Optional)
     *     prompt_loss_rate: Double (Optional)
     *     compute_classification_metrics: Boolean (Optional)
     *     classification_n_classes: Long (Optional)
     *     classification_positive_class: String (Optional)
     *     classification_betas (Optional): [
     *         double (Optional)
     *     ]
     *     suffix: String (Optional)
     * }
     * }</pre>
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created_at: long (Required)
     *     updated_at: long (Required)
     *     model: String (Required)
     *     fine_tuned_model: String (Required)
     *     organization_id: String (Required)
     *     status: String(created/running/succeeded/failed/cancelled) (Required)
     *     hyperparams (Required): {
     *         n_epochs: long (Required)
     *         batch_size: long (Required)
     *         prompt_loss_weight: double (Required)
     *         learning_rate_multiplier: double (Required)
     *         compute_classification_metrics: Boolean (Optional)
     *         classification_positive_class: String (Optional)
     *         classification_n_classes: Long (Optional)
     *     }
     *     training_files (Required): [
     *          (Required){
     *             id: String (Required)
     *             object: String (Required)
     *             bytes: long (Required)
     *             createdAt: long (Required)
     *             filename: String (Required)
     *             purpose: String (Required)
     *             status: String(uploaded/processed/pending/error/deleting/deleted) (Required)
     *             status_details: String (Optional)
     *         }
     *     ]
     *     validation_files (Required): [
     *         (recursive schema, see above)
     *     ]
     *     result_files (Required): [
     *         (recursive schema, see above)
     *     ]
     *     events (Optional): [
     *          (Optional){
     *             object: String (Required)
     *             created_at: long (Required)
     *             level: String (Required)
     *             message: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param fineTune The fineTune parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the `FineTune` object represents a legacy fine-tune job that has been created through the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createFineTuneWithResponse(BinaryData fineTune, RequestOptions requestOptions) {
        return this.serviceClient.createFineTuneWithResponse(fineTune, requestOptions);
    }

    /**
     * List your organization's fine-tuning jobs.
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     object: String (Required)
     *     data (Required): [
     *          (Required){
     *             id: String (Required)
     *             object: String (Required)
     *             created_at: long (Required)
     *             updated_at: long (Required)
     *             model: String (Required)
     *             fine_tuned_model: String (Required)
     *             organization_id: String (Required)
     *             status: String(created/running/succeeded/failed/cancelled) (Required)
     *             hyperparams (Required): {
     *                 n_epochs: long (Required)
     *                 batch_size: long (Required)
     *                 prompt_loss_weight: double (Required)
     *                 learning_rate_multiplier: double (Required)
     *                 compute_classification_metrics: Boolean (Optional)
     *                 classification_positive_class: String (Optional)
     *                 classification_n_classes: Long (Optional)
     *             }
     *             training_files (Required): [
     *                  (Required){
     *                     id: String (Required)
     *                     object: String (Required)
     *                     bytes: long (Required)
     *                     createdAt: long (Required)
     *                     filename: String (Required)
     *                     purpose: String (Required)
     *                     status: String(uploaded/processed/pending/error/deleting/deleted) (Required)
     *                     status_details: String (Optional)
     *                 }
     *             ]
     *             validation_files (Required): [
     *                 (recursive schema, see above)
     *             ]
     *             result_files (Required): [
     *                 (recursive schema, see above)
     *             ]
     *             events (Optional): [
     *                  (Optional){
     *                     object: String (Required)
     *                     created_at: long (Required)
     *                     level: String (Required)
     *                     message: String (Required)
     *                 }
     *             ]
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listFineTunesWithResponse(RequestOptions requestOptions) {
        return this.serviceClient.listFineTunesWithResponse(requestOptions);
    }

    /**
     * Gets info about the fine-tune job.
     * 
     * [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning).
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created_at: long (Required)
     *     updated_at: long (Required)
     *     model: String (Required)
     *     fine_tuned_model: String (Required)
     *     organization_id: String (Required)
     *     status: String(created/running/succeeded/failed/cancelled) (Required)
     *     hyperparams (Required): {
     *         n_epochs: long (Required)
     *         batch_size: long (Required)
     *         prompt_loss_weight: double (Required)
     *         learning_rate_multiplier: double (Required)
     *         compute_classification_metrics: Boolean (Optional)
     *         classification_positive_class: String (Optional)
     *         classification_n_classes: Long (Optional)
     *     }
     *     training_files (Required): [
     *          (Required){
     *             id: String (Required)
     *             object: String (Required)
     *             bytes: long (Required)
     *             createdAt: long (Required)
     *             filename: String (Required)
     *             purpose: String (Required)
     *             status: String(uploaded/processed/pending/error/deleting/deleted) (Required)
     *             status_details: String (Optional)
     *         }
     *     ]
     *     validation_files (Required): [
     *         (recursive schema, see above)
     *     ]
     *     result_files (Required): [
     *         (recursive schema, see above)
     *     ]
     *     events (Optional): [
     *          (Optional){
     *             object: String (Required)
     *             created_at: long (Required)
     *             level: String (Required)
     *             message: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param fineTuneId The ID of the fine-tune job.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the `FineTune` object represents a legacy fine-tune job that has been created through the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> retrieveFineTuneWithResponse(String fineTuneId, RequestOptions requestOptions) {
        return this.serviceClient.retrieveFineTuneWithResponse(fineTuneId, requestOptions);
    }

    /**
     * Get fine-grained status updates for a fine-tune job.
     * <p>
     * <strong>Query Parameters</strong>
     * </p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr>
     * <th>Name</th>
     * <th>Type</th>
     * <th>Required</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td>stream</td>
     * <td>Boolean</td>
     * <td>No</td>
     * <td>Whether to stream events for the fine-tune job. If set to true, events will be sent as
     * data-only
     * [server-sent
     * events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
     * as they become available. The stream will terminate with a `data: [DONE]` message when the
     * job is finished (succeeded, cancelled, or failed).
     * 
     * If set to false, only events generated so far will be returned.</td>
     * </tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     object: String (Required)
     *     data (Required): [
     *          (Required){
     *             object: String (Required)
     *             created_at: long (Required)
     *             level: String (Required)
     *             message: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param fineTuneId The ID of the fine-tune job to get events for.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listFineTuneEventsWithResponse(String fineTuneId, RequestOptions requestOptions) {
        return this.serviceClient.listFineTuneEventsWithResponse(fineTuneId, requestOptions);
    }

    /**
     * Immediately cancel a fine-tune job.
     * <p>
     * <strong>Response Body Schema</strong>
     * </p>
     * <pre>{@code
     * {
     *     id: String (Required)
     *     object: String (Required)
     *     created_at: long (Required)
     *     updated_at: long (Required)
     *     model: String (Required)
     *     fine_tuned_model: String (Required)
     *     organization_id: String (Required)
     *     status: String(created/running/succeeded/failed/cancelled) (Required)
     *     hyperparams (Required): {
     *         n_epochs: long (Required)
     *         batch_size: long (Required)
     *         prompt_loss_weight: double (Required)
     *         learning_rate_multiplier: double (Required)
     *         compute_classification_metrics: Boolean (Optional)
     *         classification_positive_class: String (Optional)
     *         classification_n_classes: Long (Optional)
     *     }
     *     training_files (Required): [
     *          (Required){
     *             id: String (Required)
     *             object: String (Required)
     *             bytes: long (Required)
     *             createdAt: long (Required)
     *             filename: String (Required)
     *             purpose: String (Required)
     *             status: String(uploaded/processed/pending/error/deleting/deleted) (Required)
     *             status_details: String (Optional)
     *         }
     *     ]
     *     validation_files (Required): [
     *         (recursive schema, see above)
     *     ]
     *     result_files (Required): [
     *         (recursive schema, see above)
     *     ]
     *     events (Optional): [
     *          (Optional){
     *             object: String (Required)
     *             created_at: long (Required)
     *             level: String (Required)
     *             message: String (Required)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param fineTuneId The ID of the fine-tune job to cancel.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the `FineTune` object represents a legacy fine-tune job that has been created through the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> cancelFineTuneWithResponse(String fineTuneId, RequestOptions requestOptions) {
        return this.serviceClient.cancelFineTuneWithResponse(fineTuneId, requestOptions);
    }

    /**
     * Creates a job that fine-tunes a specified model from a given dataset.
     * 
     * Response includes details of the enqueued job including job status and the name of the fine-tuned models once
     * complete.
     * 
     * [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning).
     * 
     * @param fineTune The fineTune parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the `FineTune` object represents a legacy fine-tune job that has been created through the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public FineTune createFineTune(CreateFineTuneRequest fineTune) {
        // Generated convenience method for createFineTuneWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createFineTuneWithResponse(BinaryData.fromObject(fineTune), requestOptions).getValue()
            .toObject(FineTune.class);
    }

    /**
     * List your organization's fine-tuning jobs.
     * 
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTunesResponse listFineTunes() {
        // Generated convenience method for listFineTunesWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listFineTunesWithResponse(requestOptions).getValue().toObject(ListFineTunesResponse.class);
    }

    /**
     * Gets info about the fine-tune job.
     * 
     * [Learn more about fine-tuning](/docs/guides/legacy-fine-tuning).
     * 
     * @param fineTuneId The ID of the fine-tune job.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the `FineTune` object represents a legacy fine-tune job that has been created through the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public FineTune retrieveFineTune(String fineTuneId) {
        // Generated convenience method for retrieveFineTuneWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return retrieveFineTuneWithResponse(fineTuneId, requestOptions).getValue().toObject(FineTune.class);
    }

    /**
     * Get fine-grained status updates for a fine-tune job.
     * 
     * @param fineTuneId The ID of the fine-tune job to get events for.
     * @param stream Whether to stream events for the fine-tune job. If set to true, events will be sent as
     * data-only
     * [server-sent
     * events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
     * as they become available. The stream will terminate with a `data: [DONE]` message when the
     * job is finished (succeeded, cancelled, or failed).
     * 
     * If set to false, only events generated so far will be returned.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTuneEventsResponse listFineTuneEvents(String fineTuneId, Boolean stream) {
        // Generated convenience method for listFineTuneEventsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (stream != null) {
            requestOptions.addQueryParam("stream", String.valueOf(stream));
        }
        return listFineTuneEventsWithResponse(fineTuneId, requestOptions).getValue()
            .toObject(ListFineTuneEventsResponse.class);
    }

    /**
     * Get fine-grained status updates for a fine-tune job.
     * 
     * @param fineTuneId The ID of the fine-tune job to get events for.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTuneEventsResponse listFineTuneEvents(String fineTuneId) {
        // Generated convenience method for listFineTuneEventsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listFineTuneEventsWithResponse(fineTuneId, requestOptions).getValue()
            .toObject(ListFineTuneEventsResponse.class);
    }

    /**
     * Immediately cancel a fine-tune job.
     * 
     * @param fineTuneId The ID of the fine-tune job to cancel.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the `FineTune` object represents a legacy fine-tune job that has been created through the API.
     */
    @Metadata(generated = true)
    @ServiceMethod(returns = ReturnType.SINGLE)
    public FineTune cancelFineTune(String fineTuneId) {
        // Generated convenience method for cancelFineTuneWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return cancelFineTuneWithResponse(fineTuneId, requestOptions).getValue().toObject(FineTune.class);
    }
}
