// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai;

import com.generic.ai.openai.implementation.OpenAiClientImpl;
import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.ServiceClientBuilder;
import com.generic.core.credential.KeyCredential;
import com.generic.core.http.pipeline.HttpPipeline;
import com.generic.core.http.pipeline.HttpPipelineBuilder;
import com.generic.core.http.pipeline.HttpPipelinePolicy;
import com.generic.core.http.policy.KeyCredentialPolicy;
import java.util.ArrayList;
import java.util.List;

/**
 * A builder for creating a new instance of the OpenAiClient type.
 */
@ServiceClientBuilder(
    serviceClients = {
        AudioTranscriptionsClient.class,
        AudioTranslationsClient.class,
        ChatCompletionsClient.class,
        FineTuningJobsClient.class,
        CompletionsClient.class,
        EditsClient.class,
        EmbeddingsClient.class,
        FilesClient.class,
        FineTunesClient.class,
        ModelsClient.class,
        ImagesClient.class,
        ModerationsClient.class })
public final class OpenAiClientBuilder {
    @Metadata(generated = true)
    private static final String SDK_NAME = "name";

    @Metadata(generated = true)
    private static final String SDK_VERSION = "version";

    /**
     * Create an instance of the OpenAiClientBuilder.
     */
    @Metadata(generated = true)
    public OpenAiClientBuilder() {
    }

    /*
     * The KeyCredential used for authentication.
     */
    @Metadata(generated = true)
    private KeyCredential keyCredential;

    /**
     * {@inheritDoc}.
     */
    @Metadata(generated = true)
    public OpenAiClientBuilder credential(KeyCredential keyCredential) {
        this.keyCredential = keyCredential;
        return this;
    }

    /**
     * Builds an instance of OpenAiClientImpl with the provided parameters.
     * 
     * @return an instance of OpenAiClientImpl.
     */
    @Metadata(generated = true)
    private OpenAiClientImpl buildInnerClient() {
        OpenAiClientImpl client = new OpenAiClientImpl(this.createHttpPipeline());
        return client;
    }

    @Metadata(generated = true)
    private HttpPipeline createHttpPipeline() {
        HttpPipelineBuilder httpPipelineBuilder = new HttpPipelineBuilder();
        List<HttpPipelinePolicy> policies = new ArrayList<>();
        if (keyCredential != null) {
            policies.add(new KeyCredentialPolicy("authorization", keyCredential, "Bearer"));
        }
        httpPipelineBuilder.policies(policies.toArray(new HttpPipelinePolicy[0]));
        return httpPipelineBuilder.build();
    }

    /**
     * Builds an instance of AudioTranscriptionsClient class.
     * 
     * @return an instance of AudioTranscriptionsClient.
     */
    @Metadata(generated = true)
    public AudioTranscriptionsClient buildAudioTranscriptionsClient() {
        return new AudioTranscriptionsClient(buildInnerClient().getAudioTranscriptions());
    }

    /**
     * Builds an instance of AudioTranslationsClient class.
     * 
     * @return an instance of AudioTranslationsClient.
     */
    @Metadata(generated = true)
    public AudioTranslationsClient buildAudioTranslationsClient() {
        return new AudioTranslationsClient(buildInnerClient().getAudioTranslations());
    }

    /**
     * Builds an instance of ChatCompletionsClient class.
     * 
     * @return an instance of ChatCompletionsClient.
     */
    @Metadata(generated = true)
    public ChatCompletionsClient buildChatCompletionsClient() {
        return new ChatCompletionsClient(buildInnerClient().getChatCompletions());
    }

    /**
     * Builds an instance of FineTuningJobsClient class.
     * 
     * @return an instance of FineTuningJobsClient.
     */
    @Metadata(generated = true)
    public FineTuningJobsClient buildFineTuningJobsClient() {
        return new FineTuningJobsClient(buildInnerClient().getFineTuningJobs());
    }

    /**
     * Builds an instance of CompletionsClient class.
     * 
     * @return an instance of CompletionsClient.
     */
    @Metadata(generated = true)
    public CompletionsClient buildCompletionsClient() {
        return new CompletionsClient(buildInnerClient().getCompletions());
    }

    /**
     * Builds an instance of EditsClient class.
     * 
     * @return an instance of EditsClient.
     */
    @Metadata(generated = true)
    public EditsClient buildEditsClient() {
        return new EditsClient(buildInnerClient().getEdits());
    }

    /**
     * Builds an instance of EmbeddingsClient class.
     * 
     * @return an instance of EmbeddingsClient.
     */
    @Metadata(generated = true)
    public EmbeddingsClient buildEmbeddingsClient() {
        return new EmbeddingsClient(buildInnerClient().getEmbeddings());
    }

    /**
     * Builds an instance of FilesClient class.
     * 
     * @return an instance of FilesClient.
     */
    @Metadata(generated = true)
    public FilesClient buildFilesClient() {
        return new FilesClient(buildInnerClient().getFiles());
    }

    /**
     * Builds an instance of FineTunesClient class.
     * 
     * @return an instance of FineTunesClient.
     */
    @Metadata(generated = true)
    public FineTunesClient buildFineTunesClient() {
        return new FineTunesClient(buildInnerClient().getFineTunes());
    }

    /**
     * Builds an instance of ModelsClient class.
     * 
     * @return an instance of ModelsClient.
     */
    @Metadata(generated = true)
    public ModelsClient buildModelsClient() {
        return new ModelsClient(buildInnerClient().getModels());
    }

    /**
     * Builds an instance of ImagesClient class.
     * 
     * @return an instance of ImagesClient.
     */
    @Metadata(generated = true)
    public ImagesClient buildImagesClient() {
        return new ImagesClient(buildInnerClient().getImages());
    }

    /**
     * Builds an instance of ModerationsClient class.
     * 
     * @return an instance of ModerationsClient.
     */
    @Metadata(generated = true)
    public ModerationsClient buildModerationsClient() {
        return new ModerationsClient(buildInnerClient().getModerations());
    }
}
