// Code generated by Microsoft (R) TypeSpec Code Generator.
/**
 * <!-- start generated doc -->
 * Package containing the classes for OpenAi.
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 * <!-- end generated doc -->
 */
package com.generic.ai.openai;
