// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.TypeConditions;
import com.generic.json.JsonReader;
import com.generic.json.JsonSerializable;
import com.generic.json.JsonToken;
import com.generic.json.JsonWriter;
import java.io.IOException;

/**
 * The ChatCompletionResponseMessage model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class ChatCompletionResponseMessage implements JsonSerializable<ChatCompletionResponseMessage> {
    /*
     * The role of the author of this message.
     */
    @Metadata(generated = true)
    private final ChatCompletionResponseMessageRole role;

    /*
     * The contents of the message.
     */
    @Metadata(generated = true)
    private final String content;

    /*
     * The name and arguments of a function that should be called, as generated by the model.
     */
    @Metadata(generated = true)
    private ChatCompletionResponseMessageFunctionCall functionCall;

    /**
     * Creates an instance of ChatCompletionResponseMessage class.
     * 
     * @param role the role value to set.
     * @param content the content value to set.
     */
    @Metadata(generated = true)
    private ChatCompletionResponseMessage(ChatCompletionResponseMessageRole role, String content) {
        this.role = role;
        this.content = content;
    }

    /**
     * Get the role property: The role of the author of this message.
     * 
     * @return the role value.
     */
    @Metadata(generated = true)
    public ChatCompletionResponseMessageRole getRole() {
        return this.role;
    }

    /**
     * Get the content property: The contents of the message.
     * 
     * @return the content value.
     */
    @Metadata(generated = true)
    public String getContent() {
        return this.content;
    }

    /**
     * Get the functionCall property: The name and arguments of a function that should be called, as generated by the
     * model.
     * 
     * @return the functionCall value.
     */
    @Metadata(generated = true)
    public ChatCompletionResponseMessageFunctionCall getFunctionCall() {
        return this.functionCall;
    }

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("role", this.role == null ? null : this.role.toString());
        jsonWriter.writeStringField("content", this.content);
        jsonWriter.writeJsonField("function_call", this.functionCall);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ChatCompletionResponseMessage from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ChatCompletionResponseMessage if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ChatCompletionResponseMessage.
     */
    public static ChatCompletionResponseMessage fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ChatCompletionResponseMessageRole role = null;
            String content = null;
            ChatCompletionResponseMessageFunctionCall functionCall = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("role".equals(fieldName)) {
                    role = ChatCompletionResponseMessageRole.fromString(reader.getString());
                } else if ("content".equals(fieldName)) {
                    content = reader.getString();
                } else if ("function_call".equals(fieldName)) {
                    functionCall = ChatCompletionResponseMessageFunctionCall.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            ChatCompletionResponseMessage deserializedChatCompletionResponseMessage
                = new ChatCompletionResponseMessage(role, content);
            deserializedChatCompletionResponseMessage.functionCall = functionCall;

            return deserializedChatCompletionResponseMessage;
        });
    }
}
