// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

/**
 * Defines values for CreateEditResponseFinishReason.
 */
public enum CreateEditResponseFinishReason {
    /**
     * Enum value stop.
     */
    STOP("stop"),

    /**
     * Enum value length.
     */
    LENGTH("length");

    /**
     * The actual serialized value for a CreateEditResponseFinishReason instance.
     */
    private final String value;

    CreateEditResponseFinishReason(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateEditResponseFinishReason instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateEditResponseFinishReason object, or null if unable to parse.
     */
    public static CreateEditResponseFinishReason fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateEditResponseFinishReason[] items = CreateEditResponseFinishReason.values();
        for (CreateEditResponseFinishReason item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
