// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

import com.generic.core.annotation.Metadata;
import com.generic.core.models.ExpandableStringEnum;
import java.util.Collection;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines values for CreateEmbeddingRequestModel.
 */
public final class CreateEmbeddingRequestModel implements ExpandableStringEnum<CreateEmbeddingRequestModel> {
    public static final Map<String, CreateEmbeddingRequestModel> VALUES = new ConcurrentHashMap<>();

    /**
     * Static value text-embedding-ada-002 for CreateEmbeddingRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateEmbeddingRequestModel TEXT_EMBEDDING_ADA002 = fromString("text-embedding-ada-002");

    private CreateEmbeddingRequestModel(String name) {
        VALUES.put(name, this);
    }

    /**
     * Creates or finds a CreateEmbeddingRequestModel from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding CreateEmbeddingRequestModel.
     */
    @Metadata(generated = true)
    public static CreateEmbeddingRequestModel fromString(String name) {
        if (name == null) {
            return null;
        }
        CreateEmbeddingRequestModel value = VALUES.get(name);
        if (value != null) {
            return value;
        }
        return VALUES.computeIfAbsent(name, key -> new CreateEmbeddingRequestModel(key));
    }

    /**
     * Gets known CreateEmbeddingRequestModel values.
     * 
     * @return known CreateEmbeddingRequestModel values.
     */
    @Metadata(generated = true)
    public static Collection<CreateEmbeddingRequestModel> values() {
        return VALUES.values();
    }
}
