// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

import com.generic.core.annotation.Metadata;
import com.generic.core.models.ExpandableStringEnum;
import java.util.Collection;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines values for CreateTranscriptionRequestModel.
 */
public final class CreateTranscriptionRequestModel implements ExpandableStringEnum<CreateTranscriptionRequestModel> {
    public static final Map<String, CreateTranscriptionRequestModel> VALUES = new ConcurrentHashMap<>();

    /**
     * Static value whisper-1 for CreateTranscriptionRequestModel.
     */
    @Metadata(generated = true)
    public static final CreateTranscriptionRequestModel WHISPER1 = fromString("whisper-1");

    private CreateTranscriptionRequestModel(String name) {
        VALUES.put(name, this);
    }

    /**
     * Creates or finds a CreateTranscriptionRequestModel from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding CreateTranscriptionRequestModel.
     */
    @Metadata(generated = true)
    public static CreateTranscriptionRequestModel fromString(String name) {
        if (name == null) {
            return null;
        }
        CreateTranscriptionRequestModel value = VALUES.get(name);
        if (value != null) {
            return value;
        }
        return VALUES.computeIfAbsent(name, key -> new CreateTranscriptionRequestModel(key));
    }

    /**
     * Gets known CreateTranscriptionRequestModel values.
     * 
     * @return known CreateTranscriptionRequestModel values.
     */
    @Metadata(generated = true)
    public static Collection<CreateTranscriptionRequestModel> values() {
        return VALUES.values();
    }
}
