// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.TypeConditions;
import com.generic.core.models.BinaryData;
import com.generic.json.JsonReader;
import com.generic.json.JsonSerializable;
import com.generic.json.JsonToken;
import com.generic.json.JsonWriter;
import java.io.IOException;

/**
 * The CreateImageEditRequest model.
 */
@Metadata(conditions = { TypeConditions.FLUENT })
public final class CreateImageEditRequest implements JsonSerializable<CreateImageEditRequest> {
    /*
     * A text description of the desired image(s). The maximum length is 1000 characters.
     */
    @Metadata(generated = true)
    private final String prompt;

    /*
     * The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not
     * provided, image must have transparency, which will be used as the mask.
     */
    @Metadata(generated = true)
    private final BinaryData image;

    /*
     * The filename for image
     */
    @Metadata(generated = true)
    private String imageFilename = "image";

    /*
     * An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where
     * `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions
     * as `image`.
     */
    @Metadata(generated = true)
    private BinaryData mask;

    /*
     * The filename for mask
     */
    @Metadata(generated = true)
    private String maskFilename = "mask";

    /*
     * The number of images to generate. Must be between 1 and 10.
     */
    @Metadata(generated = true)
    private Long n;

    /*
     * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     */
    @Metadata(generated = true)
    private CreateImageRequestSize size;

    /*
     * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
     */
    @Metadata(generated = true)
    private CreateImageRequestResponseFormat responseFormat;

    /*
     * The user property.
     */
    @Metadata(generated = true)
    private String user;

    /**
     * Creates an instance of CreateImageEditRequest class.
     * 
     * @param prompt the prompt value to set.
     * @param image the image value to set.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest(String prompt, BinaryData image) {
        this.prompt = prompt;
        this.image = image;
    }

    /**
     * Get the prompt property: A text description of the desired image(s). The maximum length is 1000 characters.
     * 
     * @return the prompt value.
     */
    @Metadata(generated = true)
    public String getPrompt() {
        return this.prompt;
    }

    /**
     * Get the image property: The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not
     * provided, image must have transparency, which will be used as the mask.
     * 
     * @return the image value.
     */
    @Metadata(generated = true)
    public BinaryData getImage() {
        return this.image;
    }

    /**
     * Get the imageFilename property: The filename for image.
     * 
     * @return the imageFilename value.
     */
    @Metadata(generated = true)
    public String getImageFilename() {
        return this.imageFilename;
    }

    /**
     * Set the imageFilename property: The filename for image.
     * 
     * @param imageFilename the imageFilename value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setImageFilename(String imageFilename) {
        this.imageFilename = imageFilename;
        return this;
    }

    /**
     * Get the mask property: An additional image whose fully transparent areas (e.g. where alpha is zero) indicate
     * where
     * `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions
     * as `image`.
     * 
     * @return the mask value.
     */
    @Metadata(generated = true)
    public BinaryData getMask() {
        return this.mask;
    }

    /**
     * Set the mask property: An additional image whose fully transparent areas (e.g. where alpha is zero) indicate
     * where
     * `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions
     * as `image`.
     * 
     * @param mask the mask value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setMask(BinaryData mask) {
        this.mask = mask;
        return this;
    }

    /**
     * Get the maskFilename property: The filename for mask.
     * 
     * @return the maskFilename value.
     */
    @Metadata(generated = true)
    public String getMaskFilename() {
        return this.maskFilename;
    }

    /**
     * Set the maskFilename property: The filename for mask.
     * 
     * @param maskFilename the maskFilename value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setMaskFilename(String maskFilename) {
        this.maskFilename = maskFilename;
        return this;
    }

    /**
     * Get the n property: The number of images to generate. Must be between 1 and 10.
     * 
     * @return the n value.
     */
    @Metadata(generated = true)
    public Long getN() {
        return this.n;
    }

    /**
     * Set the n property: The number of images to generate. Must be between 1 and 10.
     * 
     * @param n the n value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setN(Long n) {
        this.n = n;
        return this;
    }

    /**
     * Get the size property: The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     * 
     * @return the size value.
     */
    @Metadata(generated = true)
    public CreateImageRequestSize getSize() {
        return this.size;
    }

    /**
     * Set the size property: The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     * 
     * @param size the size value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setSize(CreateImageRequestSize size) {
        this.size = size;
        return this;
    }

    /**
     * Get the responseFormat property: The format in which the generated images are returned. Must be one of `url` or
     * `b64_json`.
     * 
     * @return the responseFormat value.
     */
    @Metadata(generated = true)
    public CreateImageRequestResponseFormat getResponseFormat() {
        return this.responseFormat;
    }

    /**
     * Set the responseFormat property: The format in which the generated images are returned. Must be one of `url` or
     * `b64_json`.
     * 
     * @param responseFormat the responseFormat value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setResponseFormat(CreateImageRequestResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }

    /**
     * Get the user property: The user property.
     * 
     * @return the user value.
     */
    @Metadata(generated = true)
    public String getUser() {
        return this.user;
    }

    /**
     * Set the user property: The user property.
     * 
     * @param user the user value to set.
     * @return the CreateImageEditRequest object itself.
     */
    @Metadata(generated = true)
    public CreateImageEditRequest setUser(String user) {
        this.user = user;
        return this;
    }

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("prompt", this.prompt);
        jsonWriter.writeUntypedField("image", this.image.toObject(Object.class));
        jsonWriter.writeStringField("image", this.imageFilename);
        if (this.mask != null) {
            jsonWriter.writeUntypedField("mask", this.mask.toObject(Object.class));
        }
        jsonWriter.writeStringField("mask", this.maskFilename);
        jsonWriter.writeNumberField("n", this.n);
        jsonWriter.writeStringField("size", this.size == null ? null : this.size.toString());
        jsonWriter.writeStringField("response_format",
            this.responseFormat == null ? null : this.responseFormat.toString());
        jsonWriter.writeStringField("user", this.user);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CreateImageEditRequest from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of CreateImageEditRequest if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the CreateImageEditRequest.
     */
    public static CreateImageEditRequest fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String prompt = null;
            BinaryData image = null;
            String imageFilename = null;
            BinaryData mask = null;
            String maskFilename = null;
            Long n = null;
            CreateImageRequestSize size = null;
            CreateImageRequestResponseFormat responseFormat = null;
            String user = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("prompt".equals(fieldName)) {
                    prompt = reader.getString();
                } else if ("image".equals(fieldName)) {
                    image = reader.getNullable(nonNullReader -> BinaryData.fromObject(nonNullReader.readUntyped()));
                } else if ("image".equals(fieldName)) {
                    imageFilename = reader.getString();
                } else if ("mask".equals(fieldName)) {
                    mask = reader.getNullable(nonNullReader -> BinaryData.fromObject(nonNullReader.readUntyped()));
                } else if ("mask".equals(fieldName)) {
                    maskFilename = reader.getString();
                } else if ("n".equals(fieldName)) {
                    n = reader.getNullable(JsonReader::getLong);
                } else if ("size".equals(fieldName)) {
                    size = CreateImageRequestSize.fromString(reader.getString());
                } else if ("response_format".equals(fieldName)) {
                    responseFormat = CreateImageRequestResponseFormat.fromString(reader.getString());
                } else if ("user".equals(fieldName)) {
                    user = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            CreateImageEditRequest deserializedCreateImageEditRequest = new CreateImageEditRequest(prompt, image);
            deserializedCreateImageEditRequest.imageFilename = imageFilename;
            deserializedCreateImageEditRequest.mask = mask;
            deserializedCreateImageEditRequest.maskFilename = maskFilename;
            deserializedCreateImageEditRequest.n = n;
            deserializedCreateImageEditRequest.size = size;
            deserializedCreateImageEditRequest.responseFormat = responseFormat;
            deserializedCreateImageEditRequest.user = user;

            return deserializedCreateImageEditRequest;
        });
    }
}
