// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.TypeConditions;
import com.generic.json.JsonReader;
import com.generic.json.JsonSerializable;
import com.generic.json.JsonToken;
import com.generic.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The ListModelsResponse model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class ListModelsResponse implements JsonSerializable<ListModelsResponse> {
    /*
     * The object property.
     */
    @Metadata(generated = true)
    private final String object;

    /*
     * The data property.
     */
    @Metadata(generated = true)
    private final List<Model> data;

    /**
     * Creates an instance of ListModelsResponse class.
     * 
     * @param object the object value to set.
     * @param data the data value to set.
     */
    @Metadata(generated = true)
    private ListModelsResponse(String object, List<Model> data) {
        this.object = object;
        this.data = data;
    }

    /**
     * Get the object property: The object property.
     * 
     * @return the object value.
     */
    @Metadata(generated = true)
    public String getObject() {
        return this.object;
    }

    /**
     * Get the data property: The data property.
     * 
     * @return the data value.
     */
    @Metadata(generated = true)
    public List<Model> getData() {
        return this.data;
    }

    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("object", this.object);
        jsonWriter.writeArrayField("data", this.data, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ListModelsResponse from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ListModelsResponse if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ListModelsResponse.
     */
    public static ListModelsResponse fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String object = null;
            List<Model> data = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("object".equals(fieldName)) {
                    object = reader.getString();
                } else if ("data".equals(fieldName)) {
                    data = reader.readArray(reader1 -> Model.fromJson(reader1));
                } else {
                    reader.skipChildren();
                }
            }
            return new ListModelsResponse(object, data);
        });
    }
}
