// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.generic.ai.openai.models;

/**
 * Defines values for OpenAiFileStatus.
 */
public enum OpenAiFileStatus {
    /**
     * Enum value uploaded.
     */
    UPLOADED("uploaded"),

    /**
     * Enum value processed.
     */
    PROCESSED("processed"),

    /**
     * Enum value pending.
     */
    PENDING("pending"),

    /**
     * Enum value error.
     */
    ERROR("error"),

    /**
     * Enum value deleting.
     */
    DELETING("deleting"),

    /**
     * Enum value deleted.
     */
    DELETED("deleted");

    /**
     * The actual serialized value for a OpenAiFileStatus instance.
     */
    private final String value;

    OpenAiFileStatus(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a OpenAiFileStatus instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed OpenAiFileStatus object, or null if unable to parse.
     */
    public static OpenAiFileStatus fromString(String value) {
        if (value == null) {
            return null;
        }
        OpenAiFileStatus[] items = OpenAiFileStatus.values();
        for (OpenAiFileStatus item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
