trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-native-tests.yml
    parameters:
      ServiceDirectory: keyvault
      TimeoutInMinutes: 240
      SupportedClouds: 'Public'
      EnvVars:
        AZURE_LOG_LEVEL: 2
      CloudConfig:
        Public:
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
      MatrixConfigs:
        - Name: Key_Vault_live_test
          Path: sdk/keyvault/native-platform-matrix.json
          Selection: sparse
          GenerateVMJobs: true
      Artifacts:
        - name: azure-security-keyvault-certificates
          groupId: com.azure
          safeName: azuresecuritykeyvaultcertificates
        - name: azure-security-keyvault-keys
          groupId: com.azure
          safeName: azuresecuritykeyvaultkeys
        - name: azure-security-keyvault-secrets
          groupId: com.azure
          safeName: azuresecuritykeyvaultsecrets
