// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.azure.messaging.eventhubs.models;

import com.azure.core.annotation.Immutable;

/**
 * A model class to hold partition ownership information.
 */
@Immutable
public class PartitionOwnership {

    private final String fullyQualifiedNamespace;
    private final String eventHubName;
    private final String consumerGroup;
    private final String partitionId;
    private final String ownerId;
    private final Long lastModifiedTime;
    private final String eTag;

    public PartitionOwnership(String fullyQualifiedNamespace, String eventHubName, String consumerGroup,
        String partitionId, String ownerId, Long lastModifiedTime, String eTag) {
        this.fullyQualifiedNamespace = fullyQualifiedNamespace;
        this.eventHubName = eventHubName;
        this.consumerGroup = consumerGroup;
        this.partitionId = partitionId;
        this.ownerId = ownerId;
        this.lastModifiedTime = lastModifiedTime;
        this.eTag = eTag;
    }

    // TODO: add javadoc
    public String getFullyQualifiedNamespace() {
        return fullyQualifiedNamespace;
    }

    /**
     * Gets the Event Hub name associated with this ownership record.
     *
     * @return The Event Hub name associated with this ownership record.
     */
    public String getEventHubName() {
        return eventHubName;
    }

    /**
     * Gets the consumer group name associated with this ownership record.
     *
     * @return The consumer group name associated with this ownership record.
     */
    public String getConsumerGroup() {
        return consumerGroup;
    }

    /**
     * Gets the partition id associated with this ownership record.
     *
     * @return The partition id associated with this ownership record.
     */
    public String getPartitionId() {
        return partitionId;
    }

    /**
     * Gets the unique event processor identifier as the owner of the partition id in this ownership record.
     *
     * @return The unique event processor identifier as the owner of the partition id in this ownership record.
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * Gets the last modified time of this ownership record as epoch millis.
     *
     * @return The last modified time of this ownership record as epoch millis.
     */
    public Long getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Gets the ETag that was generated by the last known successful update to the partition ownership record. An ETag
     * is a unique identifier * that is generated when a data record is successfully created/updated. The ETag is used
     * to achieve optimistic concurrency in a distributed event processor setup. When multiple instances of event
     * processor try to update the same partition ownership record, ETag is used to verify that the last values read by
     * the instance requesting the update is still the latest ETag for this record. If the ETag in the store does not
     * match the ETag in the update request, then the update is expected to fail as there was an update since the last
     * time an event processor read this record.
     *
     * @return The eTag for this ownership record.
     */
    public String getETag() {
        return eTag;
    }
}
