// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.documentintelligence.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Analyze operation status. */
public final class AnalyzeResultOperationStatus extends ExpandableStringEnum<AnalyzeResultOperationStatus> {
    /** The operation has not started yet. */
    @Generated public static final AnalyzeResultOperationStatus NOT_STARTED = fromString("notStarted");

    /** The operation is in progress. */
    @Generated public static final AnalyzeResultOperationStatus RUNNING = fromString("running");

    /** The operation has failed. */
    @Generated public static final AnalyzeResultOperationStatus FAILED = fromString("failed");

    /** The operation has succeeded. */
    @Generated public static final AnalyzeResultOperationStatus SUCCEEDED = fromString("succeeded");

    /**
     * Creates a new instance of AnalyzeResultOperationStatus value.
     *
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public AnalyzeResultOperationStatus() {}

    /**
     * Creates or finds a AnalyzeResultOperationStatus from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding AnalyzeResultOperationStatus.
     */
    @Generated
    @JsonCreator
    public static AnalyzeResultOperationStatus fromString(String name) {
        return fromString(name, AnalyzeResultOperationStatus.class);
    }

    /**
     * Gets known AnalyzeResultOperationStatus values.
     *
     * @return known AnalyzeResultOperationStatus values.
     */
    @Generated
    public static Collection<AnalyzeResultOperationStatus> values() {
        return values(AnalyzeResultOperationStatus.class);
    }
}
