// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.serialization.xml.XmlReader;
import io.clientcore.core.serialization.xml.XmlSerializable;
import io.clientcore.core.serialization.xml.XmlToken;
import io.clientcore.core.serialization.xml.XmlWriter;
import java.util.ArrayList;
import java.util.List;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * Represents the Apache Arrow configuration.
 */
@Metadata(properties = { MetadataProperties.IMMUTABLE })
public final class ArrowConfiguration implements XmlSerializable<ArrowConfiguration> {
    /*
     * The Apache Arrow schema
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final List<ArrowField> schema;

    /**
     * Creates an instance of ArrowConfiguration class.
     * 
     * @param schema the schema value to set.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public ArrowConfiguration(List<ArrowField> schema) {
        this.schema = schema;
    }

    /**
     * Get the schema property: The Apache Arrow schema.
     * 
     * @return the schema value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public List<ArrowField> getSchema() {
        return this.schema;
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty() ? "ArrowConfiguration" : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        if (this.schema != null) {
            xmlWriter.writeStartElement("Schema");
            for (ArrowField element : this.schema) {
                xmlWriter.writeXml(element, "Field");
            }
            xmlWriter.writeEndElement();
        }
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of ArrowConfiguration from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of ArrowConfiguration if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the ArrowConfiguration.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static ArrowConfiguration fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of ArrowConfiguration from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of ArrowConfiguration if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the ArrowConfiguration.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static ArrowConfiguration fromXml(XmlReader xmlReader, String rootElementName) throws XMLStreamException {
        String finalRootElementName
            = rootElementName == null || rootElementName.isEmpty() ? "ArrowConfiguration" : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            List<ArrowField> schema = null;
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("Schema".equals(elementName.getLocalPart())) {
                    while (reader.nextElement() != XmlToken.END_ELEMENT) {
                        elementName = reader.getElementName();
                        if ("Field".equals(elementName.getLocalPart())) {
                            if (schema == null) {
                                schema = new ArrayList<>();
                            }
                            schema.add(ArrowField.fromXml(reader, "Field"));
                        } else {
                            reader.skipElement();
                        }
                    }
                } else {
                    reader.skipElement();
                }
            }
            return new ArrowConfiguration(schema);
        });
    }
}
