// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.serialization.xml.XmlReader;
import io.clientcore.core.serialization.xml.XmlSerializable;
import io.clientcore.core.serialization.xml.XmlToken;
import io.clientcore.core.serialization.xml.XmlWriter;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * Represents a single block in a block blob. It describes the block's ID and size.
 */
@Metadata(properties = { MetadataProperties.IMMUTABLE })
public final class Block implements XmlSerializable<Block> {
    /*
     * The base64 encoded block ID.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final byte[] name;

    /*
     * The block size in bytes.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final long size;

    /**
     * Creates an instance of Block class.
     * 
     * @param name the name value to set.
     * @param size the size value to set.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private Block(byte[] name, long size) {
        this.name = name;
        this.size = size;
    }

    /**
     * Get the name property: The base64 encoded block ID.
     * 
     * @return the name value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public byte[] getName() {
        return this.name;
    }

    /**
     * Get the size property: The block size in bytes.
     * 
     * @return the size value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public long getSize() {
        return this.size;
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty() ? "Block" : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        xmlWriter.writeBinaryElement("Name", this.name);
        xmlWriter.writeLongElement("Size", this.size);
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of Block from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of Block if the XmlReader was pointing to an instance of it, or null if it was pointing to
     * XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the Block.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static Block fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of Block from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of Block if the XmlReader was pointing to an instance of it, or null if it was pointing to
     * XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the Block.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static Block fromXml(XmlReader xmlReader, String rootElementName) throws XMLStreamException {
        String finalRootElementName = rootElementName == null || rootElementName.isEmpty() ? "Block" : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            byte[] name = null;
            long size = 0L;
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("Name".equals(elementName.getLocalPart())) {
                    name = reader.getBinaryElement();
                } else if ("Size".equals(elementName.getLocalPart())) {
                    size = reader.getLongElement();
                } else {
                    reader.skipElement();
                }
            }
            return new Block(name, size);
        });
    }
}
