// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.serialization.xml.XmlReader;
import io.clientcore.core.serialization.xml.XmlSerializable;
import io.clientcore.core.serialization.xml.XmlToken;
import io.clientcore.core.serialization.xml.XmlWriter;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * An Azure Storage container.
 */
@Metadata(properties = { MetadataProperties.IMMUTABLE })
public final class ContainerItem implements XmlSerializable<ContainerItem> {
    /*
     * The name of the container.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final String name;

    /*
     * Whether the container is deleted.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private Boolean delete;

    /*
     * The version of the container.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private String version;

    /*
     * The properties of the container.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final ContainerProperties properties;

    /*
     * The metadata of the container.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private Map<String, String> metadata;

    /**
     * Creates an instance of ContainerItem class.
     * 
     * @param name the name value to set.
     * @param properties the properties value to set.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private ContainerItem(String name, ContainerProperties properties) {
        this.name = name;
        this.properties = properties;
    }

    /**
     * Get the name property: The name of the container.
     * 
     * @return the name value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public String getName() {
        return this.name;
    }

    /**
     * Get the delete property: Whether the container is deleted.
     * 
     * @return the delete value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public Boolean isDelete() {
        return this.delete;
    }

    /**
     * Get the version property: The version of the container.
     * 
     * @return the version value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public String getVersion() {
        return this.version;
    }

    /**
     * Get the properties property: The properties of the container.
     * 
     * @return the properties value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public ContainerProperties getProperties() {
        return this.properties;
    }

    /**
     * Get the metadata property: The metadata of the container.
     * 
     * @return the metadata value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public Map<String, String> getMetadata() {
        return this.metadata;
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty() ? "Container" : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        xmlWriter.writeStringElement("Name", this.name);
        xmlWriter.writeBooleanElement("Deleted", this.delete);
        xmlWriter.writeStringElement("Version", this.version);
        xmlWriter.writeXml(this.properties, "Properties");
        if (this.metadata != null) {
            xmlWriter.writeStartElement("Metadata");
            for (Map.Entry<String, String> entry : this.metadata.entrySet()) {
                xmlWriter.writeStringElement(entry.getKey(), entry.getValue());
            }
            xmlWriter.writeEndElement();
        }
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of ContainerItem from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of ContainerItem if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the ContainerItem.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static ContainerItem fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of ContainerItem from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of ContainerItem if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the ContainerItem.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static ContainerItem fromXml(XmlReader xmlReader, String rootElementName) throws XMLStreamException {
        String finalRootElementName
            = rootElementName == null || rootElementName.isEmpty() ? "Container" : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            String name = null;
            Boolean delete = null;
            String version = null;
            ContainerProperties properties = null;
            Map<String, String> metadata = null;
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("Name".equals(elementName.getLocalPart())) {
                    name = reader.getStringElement();
                } else if ("Deleted".equals(elementName.getLocalPart())) {
                    delete = reader.getNullableElement(Boolean::parseBoolean);
                } else if ("Version".equals(elementName.getLocalPart())) {
                    version = reader.getStringElement();
                } else if ("Properties".equals(elementName.getLocalPart())) {
                    properties = ContainerProperties.fromXml(reader, "Properties");
                } else if ("Metadata".equals(elementName.getLocalPart())) {
                    while (reader.nextElement() != XmlToken.END_ELEMENT) {
                        if (metadata == null) {
                            metadata = new LinkedHashMap<>();
                        }
                        metadata.put(reader.getElementName().getLocalPart(), reader.getStringElement());
                    }
                } else {
                    reader.skipElement();
                }
            }
            ContainerItem deserializedContainerItem = new ContainerItem(name, properties);
            deserializedContainerItem.delete = delete;
            deserializedContainerItem.version = version;
            deserializedContainerItem.metadata = metadata;

            return deserializedContainerItem;
        });
    }
}
