// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.serialization.xml.XmlReader;
import io.clientcore.core.serialization.xml.XmlSerializable;
import io.clientcore.core.serialization.xml.XmlToken;
import io.clientcore.core.serialization.xml.XmlWriter;
import java.util.ArrayList;
import java.util.List;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * The result of a Filter Blobs API call.
 */
@Metadata(properties = { MetadataProperties.IMMUTABLE })
public final class FilterBlobSegment implements XmlSerializable<FilterBlobSegment> {
    /*
     * The service endpoint.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final String serviceEndpoint;

    /*
     * The filter for the blobs.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final String where;

    /*
     * The blob segment.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final List<FilterBlobItem> blobs;

    /*
     * The next marker of the blobs.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private String nextMarker;

    /**
     * Creates an instance of FilterBlobSegment class.
     * 
     * @param serviceEndpoint the serviceEndpoint value to set.
     * @param where the where value to set.
     * @param blobs the blobs value to set.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private FilterBlobSegment(String serviceEndpoint, String where, List<FilterBlobItem> blobs) {
        this.serviceEndpoint = serviceEndpoint;
        this.where = where;
        this.blobs = blobs;
    }

    /**
     * Get the serviceEndpoint property: The service endpoint.
     * 
     * @return the serviceEndpoint value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public String getServiceEndpoint() {
        return this.serviceEndpoint;
    }

    /**
     * Get the where property: The filter for the blobs.
     * 
     * @return the where value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public String getWhere() {
        return this.where;
    }

    /**
     * Get the blobs property: The blob segment.
     * 
     * @return the blobs value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public List<FilterBlobItem> getBlobs() {
        return this.blobs;
    }

    /**
     * Get the nextMarker property: The next marker of the blobs.
     * 
     * @return the nextMarker value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public String getNextMarker() {
        return this.nextMarker;
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty() ? "EnumerationResults" : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        xmlWriter.writeStringAttribute("ServiceEndpoint", this.serviceEndpoint);
        xmlWriter.writeStringElement("Where", this.where);
        if (this.blobs != null) {
            xmlWriter.writeStartElement("Blobs");
            for (FilterBlobItem element : this.blobs) {
                xmlWriter.writeXml(element, "Blob");
            }
            xmlWriter.writeEndElement();
        }
        xmlWriter.writeStringElement("NextMarker", this.nextMarker);
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of FilterBlobSegment from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of FilterBlobSegment if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the FilterBlobSegment.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static FilterBlobSegment fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of FilterBlobSegment from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of FilterBlobSegment if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the FilterBlobSegment.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static FilterBlobSegment fromXml(XmlReader xmlReader, String rootElementName) throws XMLStreamException {
        String finalRootElementName
            = rootElementName == null || rootElementName.isEmpty() ? "EnumerationResults" : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            String where = null;
            List<FilterBlobItem> blobs = null;
            String nextMarker = null;
            String serviceEndpoint = reader.getStringAttribute(null, "ServiceEndpoint");
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("Where".equals(elementName.getLocalPart())) {
                    where = reader.getStringElement();
                } else if ("Blobs".equals(elementName.getLocalPart())) {
                    while (reader.nextElement() != XmlToken.END_ELEMENT) {
                        elementName = reader.getElementName();
                        if ("Blob".equals(elementName.getLocalPart())) {
                            if (blobs == null) {
                                blobs = new ArrayList<>();
                            }
                            blobs.add(FilterBlobItem.fromXml(reader, "Blob"));
                        } else {
                            reader.skipElement();
                        }
                    }
                } else if ("NextMarker".equals(elementName.getLocalPart())) {
                    nextMarker = reader.getStringElement();
                } else {
                    reader.skipElement();
                }
            }
            FilterBlobSegment deserializedFilterBlobSegment = new FilterBlobSegment(serviceEndpoint, where, blobs);
            deserializedFilterBlobSegment.nextMarker = nextMarker;

            return deserializedFilterBlobSegment;
        });
    }
}
