// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.serialization.xml.XmlReader;
import io.clientcore.core.serialization.xml.XmlSerializable;
import io.clientcore.core.serialization.xml.XmlToken;
import io.clientcore.core.serialization.xml.XmlWriter;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * The page range.
 */
@Metadata(properties = { MetadataProperties.IMMUTABLE })
public final class PageRange implements XmlSerializable<PageRange> {
    /*
     * The start of the byte range.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final long start;

    /*
     * The end of the byte range.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final long end;

    /**
     * Creates an instance of PageRange class.
     * 
     * @param start the start value to set.
     * @param end the end value to set.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private PageRange(long start, long end) {
        this.start = start;
        this.end = end;
    }

    /**
     * Get the start property: The start of the byte range.
     * 
     * @return the start value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public long getStart() {
        return this.start;
    }

    /**
     * Get the end property: The end of the byte range.
     * 
     * @return the end value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public long getEnd() {
        return this.end;
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty() ? "PageRange" : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        xmlWriter.writeLongElement("Start", this.start);
        xmlWriter.writeLongElement("End", this.end);
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of PageRange from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of PageRange if the XmlReader was pointing to an instance of it, or null if it was pointing
     * to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the PageRange.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static PageRange fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of PageRange from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of PageRange if the XmlReader was pointing to an instance of it, or null if it was pointing
     * to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the PageRange.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static PageRange fromXml(XmlReader xmlReader, String rootElementName) throws XMLStreamException {
        String finalRootElementName
            = rootElementName == null || rootElementName.isEmpty() ? "PageRange" : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            long start = 0L;
            long end = 0L;
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("Start".equals(elementName.getLocalPart())) {
                    start = reader.getLongElement();
                } else if ("End".equals(elementName.getLocalPart())) {
                    end = reader.getLongElement();
                } else {
                    reader.skipElement();
                }
            }
            return new PageRange(start, end);
        });
    }
}
