// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

/**
 * The query format type.
 */
public enum QueryType {
    /**
     * The query format type is delimited.
     */
    DELIMITED("delimited"),

    /**
     * The query format type is JSON.
     */
    JSON("json"),

    /**
     * The query format type is Apache Arrow.
     */
    ARROW("arrow"),

    /**
     * The query format type is Parquet.
     */
    PARQUET("parquet");

    /**
     * The actual serialized value for a QueryType instance.
     */
    private final String value;

    QueryType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a QueryType instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed QueryType object, or null if unable to parse.
     */
    public static QueryType fromString(String value) {
        if (value == null) {
            return null;
        }
        QueryType[] items = QueryType.values();
        for (QueryType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
