// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.storage.blob.models;

import io.clientcore.core.annotations.Metadata;
import io.clientcore.core.annotations.MetadataProperties;
import io.clientcore.core.serialization.xml.XmlReader;
import io.clientcore.core.serialization.xml.XmlSerializable;
import io.clientcore.core.serialization.xml.XmlToken;
import io.clientcore.core.serialization.xml.XmlWriter;
import javax.xml.namespace.QName;
import javax.xml.stream.XMLStreamException;

/**
 * The signed identifier.
 */
@Metadata(properties = { MetadataProperties.IMMUTABLE })
public final class SignedIdentifier implements XmlSerializable<SignedIdentifier> {
    /*
     * The unique ID for the signed identifier.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final String id;

    /*
     * The access policy for the signed identifier.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    private final AccessPolicy accessPolicy;

    /**
     * Creates an instance of SignedIdentifier class.
     * 
     * @param id the id value to set.
     * @param accessPolicy the accessPolicy value to set.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public SignedIdentifier(String id, AccessPolicy accessPolicy) {
        this.id = id;
        this.accessPolicy = accessPolicy;
    }

    /**
     * Get the id property: The unique ID for the signed identifier.
     * 
     * @return the id value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public String getId() {
        return this.id;
    }

    /**
     * Get the accessPolicy property: The access policy for the signed identifier.
     * 
     * @return the accessPolicy value.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public AccessPolicy getAccessPolicy() {
        return this.accessPolicy;
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        return toXml(xmlWriter, null);
    }

    @Metadata(properties = { MetadataProperties.GENERATED })
    @Override
    public XmlWriter toXml(XmlWriter xmlWriter, String rootElementName) throws XMLStreamException {
        rootElementName = rootElementName == null || rootElementName.isEmpty() ? "SignedIdentifier" : rootElementName;
        xmlWriter.writeStartElement(rootElementName);
        xmlWriter.writeStringElement("Id", this.id);
        xmlWriter.writeXml(this.accessPolicy, "AccessPolicy");
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of SignedIdentifier from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @return An instance of SignedIdentifier if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the SignedIdentifier.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static SignedIdentifier fromXml(XmlReader xmlReader) throws XMLStreamException {
        return fromXml(xmlReader, null);
    }

    /**
     * Reads an instance of SignedIdentifier from the XmlReader.
     * 
     * @param xmlReader The XmlReader being read.
     * @param rootElementName Optional root element name to override the default defined by the model. Used to support
     * cases where the model can deserialize from different root element names.
     * @return An instance of SignedIdentifier if the XmlReader was pointing to an instance of it, or null if it was
     * pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing any required properties.
     * @throws XMLStreamException If an error occurs while reading the SignedIdentifier.
     */
    @Metadata(properties = { MetadataProperties.GENERATED })
    public static SignedIdentifier fromXml(XmlReader xmlReader, String rootElementName) throws XMLStreamException {
        String finalRootElementName
            = rootElementName == null || rootElementName.isEmpty() ? "SignedIdentifier" : rootElementName;
        return xmlReader.readObject(finalRootElementName, reader -> {
            String id = null;
            AccessPolicy accessPolicy = null;
            while (reader.nextElement() != XmlToken.END_ELEMENT) {
                QName elementName = reader.getElementName();

                if ("Id".equals(elementName.getLocalPart())) {
                    id = reader.getStringElement();
                } else if ("AccessPolicy".equals(elementName.getLocalPart())) {
                    accessPolicy = AccessPolicy.fromXml(reader, "AccessPolicy");
                } else {
                    reader.skipElement();
                }
            }
            return new SignedIdentifier(id, accessPolicy);
        });
    }
}
